In [ ]:
%pip install pandas openpyxl

Collecting pandas
  Downloading pandas-3.0.6-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\siddeshwar\desktop\nfip-assessment\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in c:\users\siddeshwar\desktop\nfip-assessment\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.7 MB 10.1 MB/s eta 0:00:01
   ----------------- ---------------------- 4.2/9.7 MB 11.0 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.7 MB 10.3 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 9.9 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 9.8 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 9.1 MB/s eta 0:00:00
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading numpy-2.5.3-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 6.7 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.6 MB 7.6 MB/s eta 0:00:02
   --------------- ------------------------ 5.0/12.6 MB 8.6 MB/s eta 0:00:01
   -------------------- ------------------- 6.6/12.6 MB 8.4 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 8.0 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 7.3 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 7.9 MB/s eta 0:00:00
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, et-xmlfile, pandas, openpyxl
Successfully installed et-xmlfile-2.0.0 numpy-2.5.3 openpyxl-3.1.5 pandas-3.0.6 tzdata-2026.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Understanding data and finding anomalies

In [ ]:
import pandas as pd

# Read CSV
df = pd.read_csv("claims.csv")

# Print column name and data type
print(f"Total columns: {len(df.columns)}\n")

for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col} --> {df[col].dtype}")

Total columns: 31

1. claim_ref --> str
2. source_system --> str
3. dateOfLoss --> str
4. yearOfLoss --> int64
5. state --> str
6. reportedZipCode --> str
7. countyCode --> float64
8. latitude --> float64
9. longitude --> float64
10. floodEvent --> str
11. causeOfDamage --> str
12. ratedFloodZone --> str
13. occupancyType --> int64
14. numberOfFloorsInTheInsuredBuilding --> float64
15. originalConstructionDate --> str
16. elevatedBuildingIndicator --> int64
17. primaryResidenceIndicator --> int64
18. totalBuildingInsuranceCoverage --> float64
19. totalContentsInsuranceCoverage --> float64
20. buildingPropertyValue --> float64
21. buildingReplacementCost --> float64
22. buildingDamageAmount --> float64
23. contentsDamageAmount --> float64
24. waterDepth --> float64
25. floodWaterDuration --> float64
26. amountPaidOnBuildingClaim --> float64
27. amountPaidOnContentsClaim --> float64
28. netBuildingPaymentAmount --> float64
29. nonPaymentReasonBuilding --> float64
30. openDate --> str
31. mostRecentPaymentDate --> str

In [ ]:
df.head()

,claim_ref,source_system,dateOfLoss,yearOfLoss,state,reportedZipCode,countyCode,latitude,longitude,floodEvent,...,buildingDamageAmount,contentsDamageAmount,waterDepth,floodWaterDuration,amountPaidOnBuildingClaim,amountPaidOnContentsClaim,netBuildingPaymentAmount,nonPaymentReasonBuilding,openDate,mostRecentPaymentDate
0,CLM-6119947,core,2018-04-13T00:00:00.000Z,2018,HI,96734,15003.0,21.4,-157.7,NaN,...,15092.0,NaN,NaN,0.0,13841.58,0.0,13841.58,NaN,2018-04-26T00:00:00.000Z,2018-05-21T00:00:00.000Z
1,CLM-5642877,core,2021-09-01T00:00:00.000Z,2021,MA,1906,25009.0,42.4,-71.0,Hurricane Ida,...,0.0,0.0,NaN,NaN,0.00,0.0,0.00,6.0,2021-09-02T00:00:00.000Z,2021-09-22T00:00:00.000Z
2,CLM-7518535,core,2020-05-20T00:00:00.000Z,2020,MI,48640,26111.0,43.6,-84.3,NaN,...,44478.0,NaN,2.0,NaN,5000.00,0.0,5000.00,NaN,2020-05-20T00:00:00.000Z,2020-06-18T00:00:00.000Z
3,CLM-6796433,core,2024-09-26T00:00:00.000Z,2024,FL,33634,12057.0,28.0,-82.6,Hurricane Helene,...,100212.0,NaN,1.0,NaN,90211.66,0.0,90211.66,NaN,2024-09-30T00:00:00.000Z,2024-12-04T00:00:00.000Z
4,CLM-5558178,core,2024-09-26T00:00:00.000Z,2024,FL,33710,12103.0,27.8,-82.8,Hurricane Helene,...,153834.0,NaN,2.0,NaN,143833.51,0.0,143833.51,NaN,2024-09-28T00:00:00.000Z,2025-02-23T00:00:00.000Z

In [ ]:
print("Dataset size:", df.shape)

Dataset size: (2040, 31)

In [ ]:
# Missing values per column
missing = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing %": df.isna().mean() * 100
})

# Sort by highest missing percentage
missing = missing.sort_values("Missing %", ascending=False)

print(missing)

                                    Missing Count  Missing %
nonPaymentReasonBuilding                     1651  80.931373
floodWaterDuration                           1609  78.872549
contentsDamageAmount                          904  44.313725
floodEvent                                    564  27.647059
waterDepth                                    308  15.098039
buildingDamageAmount                          220  10.784314
buildingPropertyValue                         220  10.784314
buildingReplacementCost                       220  10.784314
amountPaidOnContentsClaim                     194   9.509804
mostRecentPaymentDate                         194   9.509804
amountPaidOnBuildingClaim                     192   9.411765
causeOfDamage                                  29   1.421569
originalConstructionDate                       14   0.686275
latitude                                       14   0.686275
longitude                                      14   0.686275
numberOfFloorsInTheInsuredBuilding             10   0.490196
countyCode                                      9   0.441176
ratedFloodZone                                  5   0.245098
source_system                                   0   0.000000
dateOfLoss                                      0   0.000000
reportedZipCode                                 0   0.000000
state                                           0   0.000000
claim_ref                                       0   0.000000
occupancyType                                   0   0.000000
yearOfLoss                                      0   0.000000
totalBuildingInsuranceCoverage                  0   0.000000
totalContentsInsuranceCoverage                  0   0.000000
elevatedBuildingIndicator                       0   0.000000
primaryResidenceIndicator                       0   0.000000
netBuildingPaymentAmount                        0   0.000000
openDate                                        0   0.000000

In [ ]:
# Separate columns by type
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()
numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()

print("Categorical:")
print(categorical_cols)

print("\nNumeric:")
print(numeric_cols)

# Unique values for categorical columns
for col in categorical_cols:
    print(f"\n{'='*60}")
    print(col)
    print("Unique:", df[col].nunique())
    print(df[col].value_counts(dropna=False).head(30))

Categorical:
['claim_ref', 'source_system', 'dateOfLoss', 'state', 'reportedZipCode', 'floodEvent', 'causeOfDamage', 'ratedFloodZone', 'originalConstructionDate', 'openDate', 'mostRecentPaymentDate']

Numeric:
['yearOfLoss', 'countyCode', 'latitude', 'longitude', 'occupancyType', 'numberOfFloorsInTheInsuredBuilding', 'elevatedBuildingIndicator', 'primaryResidenceIndicator', 'totalBuildingInsuranceCoverage', 'totalContentsInsuranceCoverage', 'buildingPropertyValue', 'buildingReplacementCost', 'buildingDamageAmount', 'contentsDamageAmount', 'waterDepth', 'floodWaterDuration', 'amountPaidOnBuildingClaim', 'amountPaidOnContentsClaim', 'netBuildingPaymentAmount', 'nonPaymentReasonBuilding']

============================================================
claim_ref
Unique: 2040
claim_ref
CLM-6119947      1
CLM-5642877      1
CLM-7518535      1
CLM-6796433      1
CLM-5558178      1
CLM-7658990      1
CLM-6515202      1
CLM-7046214      1
CLM-5976757      1
CLM-5813447      1
CLM-6726350      1
CLM-6830121      1
CLM-7820778      1
CLM-7822961      1
CLM-5576313      1
CLM-7455343      1
CLM-8058795      1
CLM-6596012      1
CLM-7062825      1
CLM-6053933      1
CLM-6223381      1
CLM-5637999      1
CLM-7061589      1
CLM-7806166      1
CLM-6278537      1
CLM-8168400      1
CLM-7130407      1
CLM-6166678      1
CLM-8054536      1
CLM-6839569-R    1
Name: count, dtype: int64

============================================================
source_system
Unique: 2
source_system
core          1917
legacy_bdx     123
Name: count, dtype: int64

============================================================
dateOfLoss
Unique: 611
dateOfLoss
2024-09-26T00:00:00.000Z    225
2022-09-28T00:00:00.000Z    201
2021-08-29T00:00:00.000Z     89
2024-10-09T00:00:00.000Z     71
2021-09-01T00:00:00.000Z     64
2024-09-27T00:00:00.000Z     55
2018-09-14T00:00:00.000Z     55
2019-09-19T00:00:00.000Z     44
2024-10-10T00:00:00.000Z     38
2020-09-16T00:00:00.000Z     31
2022-09-29T00:00:00.000Z     28
2023-08-30T00:00:00.000Z     23
2018-10-10T00:00:00.000Z     19
2023-04-12T00:00:00.000Z     16
2018-09-13T00:00:00.000Z     15
2024-07-08T00:00:00.000Z     13
2021-05-17T00:00:00.000Z     13
2021-09-02T00:00:00.000Z     13
2020-10-09T00:00:00.000Z     11
2024-09-11T00:00:00.000Z     11
2020-07-26T00:00:00.000Z     10
2022-09-27T00:00:00.000Z     10
2022-09-30T00:00:00.000Z     10
26-09-2024                   10
28-09-2022                   10
2018-09-15T00:00:00.000Z      9
2019-03-15T00:00:00.000Z      9
2020-11-11T00:00:00.000Z      9
2019-07-10T00:00:00.000Z      9
2020-08-04T00:00:00.000Z      9
Name: count, dtype: int64

============================================================
state
Unique: 47
state
FL    843
LA    212
TX    173
NC    143
NJ     66
NY     64
PA     53
AL     33
SC     32
CA     29
KY     29
MS     27
IL     25
MO     25
GA     22
MI     19
IN     18
VA     18
MD     17
MA     15
WV     15
CT     14
WA     13
OH     13
WI     13
TN     13
ME     11
AR      9
HI      7
NE      7
Name: count, dtype: int64

============================================================
reportedZipCode
Unique: 1047
reportedZipCode
33908    40
33957    35
70068    29
33706    26
33708    23
33931    20
34223    19
34102    18
33904    15
33703    15
34652    14
33917    13
34217    13
34224    11
33702    11
33315    11
33615    11
70458    11
28560    11
34103    11
34698    10
33950    10
70065    10
34429    10
34134    10
33914     9
34242     9
32127     9
32168     9
34667     9
Name: count, dtype: int64

============================================================
floodEvent
Unique: 62
floodEvent
NaN                                 564
Hurricane Helene                    302
Hurricane Ian                       267
Hurricane Ida                       181
Hurricane Milton                    121
Hurricane Florence                  101
Tropical Storm Imelda                55
Hurricane Sally                      41
Hurricane Idalia                     30
Hurricane Michael                    25
Hurricane Eta                        23
April Florida Flooding               22
Hurricane Isaias                     17
2021 Mid-Spring Severe Storms        17
Hurricane Beryl                      14
Hurricane Delta                      13
California Atmospheric River         13
Tropical Storm Barry                 12
Hurricane Francine                   12
Hurricane Hanna                      11
Hurricane Debby                      11
2026-06-Arthur-TS                    11
Central U.S. April Flooding          10
Late July Flooding                   10
June South Florida Flooding          10
Tropical Storm Claudette              9
Hurricane Zeta                        9
Late-September New York Flooding      8
December Nor'easter                   8
March 2019 Midwest Flooding           8
Name: count, dtype: int64

============================================================
causeOfDamage
Unique: 6
causeOfDamage
4      913
1      455
2      399
0      239
NaN     29
D        3
3        2
Name: count, dtype: int64

============================================================
ratedFloodZone
Unique: 32
ratedFloodZone
AE     1253
X       430
A        94
VE       66
ae       42
AH       31
C        26
AO       20
x        13
B        12
A08       6
NaN       5
A99       5
A13       4
A10       4
A09       3
A04       3
A05       2
A15       2
A07       2
A01       2
a         2
ah        2
A12       2
AHB       1
A11       1
A18       1
A02       1
V16       1
AOB       1
Name: count, dtype: int64

============================================================
originalConstructionDate
Unique: 807
originalConstructionDate
1970-01-01T00:00:00.000Z    34
1974-01-01T00:00:00.000Z    34
1978-01-01T00:00:00.000Z    31
1980-01-01T00:00:00.000Z    29
1968-01-01T00:00:00.000Z    28
1955-01-01T00:00:00.000Z    26
1960-01-01T00:00:00.000Z    25
1979-01-01T00:00:00.000Z    24
1982-01-01T00:00:00.000Z    23
1950-01-01T00:00:00.000Z    22
1971-01-01T00:00:00.000Z    21
1975-01-01T00:00:00.000Z    21
1973-01-01T00:00:00.000Z    21
1965-01-01T00:00:00.000Z    20
1985-01-01T00:00:00.000Z    19
1969-01-01T00:00:00.000Z    19
1972-01-01T00:00:00.000Z    19
1964-01-01T00:00:00.000Z    18
1987-01-01T00:00:00.000Z    18
1963-01-01T00:00:00.000Z    18
1990-01-01T00:00:00.000Z    17
1986-01-01T00:00:00.000Z    16
1974-07-01T00:00:00.000Z    16
1958-01-01T00:00:00.000Z    15
1988-01-01T00:00:00.000Z    15
1984-01-01T00:00:00.000Z    15
2000-01-01T00:00:00.000Z    15
1954-01-01T00:00:00.000Z    15
1956-01-01T00:00:00.000Z    14
NaN                         14
Name: count, dtype: int64

============================================================
openDate
Unique: 794
openDate
2024-09-27T00:00:00.000Z    84
2024-09-30T00:00:00.000Z    49
2021-09-02T00:00:00.000Z    46
2022-09-30T00:00:00.000Z    45
2024-09-28T00:00:00.000Z    33
2022-10-03T00:00:00.000Z    33
2022-10-04T00:00:00.000Z    30
2024-10-01T00:00:00.000Z    28
2024-10-11T00:00:00.000Z    25
2022-09-29T00:00:00.000Z    22
2024-10-02T00:00:00.000Z    21
2019-09-19T00:00:00.000Z    20
2022-10-05T00:00:00.000Z    19
2024-10-10T00:00:00.000Z    18
2018-09-17T00:00:00.000Z    18
2021-09-03T00:00:00.000Z    17
2021-08-31T00:00:00.000Z    17
2022-10-01T00:00:00.000Z    17
2021-09-01T00:00:00.000Z    16
2019-09-20T00:00:00.000Z    16
2024-10-14T00:00:00.000Z    15
2018-09-18T00:00:00.000Z    14
2024-09-29T00:00:00.000Z    13
2022-10-06T00:00:00.000Z    13
2023-04-13T00:00:00.000Z    12
2024-10-03T00:00:00.000Z    11
2022-10-02T00:00:00.000Z    11
2023-08-30T00:00:00.000Z    11
2024-10-16T00:00:00.000Z    10
2024-10-15T00:00:00.000Z    10
Name: count, dtype: int64

============================================================
mostRecentPaymentDate
Unique: 1116
mostRecentPaymentDate
NaN                         194
2024-12-15T00:00:00.000Z     19
2024-12-22T00:00:00.000Z     10
2024-11-24T00:00:00.000Z     10
2025-01-19T00:00:00.000Z      9
2024-12-08T00:00:00.000Z      9
2024-11-10T00:00:00.000Z      9
2025-01-12T00:00:00.000Z      9
2025-01-14T00:00:00.000Z      7
2022-12-04T00:00:00.000Z      7
2025-02-23T00:00:00.000Z      6
1942-10-12T00:00:00.000Z      6
2018-10-03T00:00:00.000Z      6
2024-12-27T00:00:00.000Z      6
2021-11-23T00:00:00.000Z      6
2025-04-30T00:00:00.000Z      6
2021-10-11T00:00:00.000Z      6
2023-01-08T00:00:00.000Z      6
2024-12-19T00:00:00.000Z      6
2023-02-12T00:00:00.000Z      6
2025-02-20T00:00:00.000Z      6
2018-10-08T00:00:00.000Z      6
2021-11-03T00:00:00.000Z      6
2022-12-22T00:00:00.000Z      5
2025-02-19T00:00:00.000Z      5
2021-10-29T00:00:00.000Z      5
2023-01-22T00:00:00.000Z      5
2025-02-28T00:00:00.000Z      5
2018-11-29T00:00:00.000Z      5
2018-10-17T00:00:00.000Z      5
Name: count, dtype: int64

C:\Users\SIDDESHWAR\AppData\Local\Temp\ipykernel_35820\975322498.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

In [ ]:
date_cols = [
    "dateOfLoss",
    "originalConstructionDate",
    "openDate",
    "mostRecentPaymentDate"
]

for col in date_cols:
    parsed = pd.to_datetime(df[col], errors="coerce", utc=True)

    print(f"\n{'='*70}")
    print(col)
    print("Original non-null:", df[col].notna().sum())
    print("Failed to parse:", parsed.notna().sum(), "success")
    print("Min:", parsed.min())
    print("Max:", parsed.max())

======================================================================
dateOfLoss
Original non-null: 2040
Failed to parse: 1917 success
Min: 2018-01-04 00:00:00+00:00
Max: 2026-08-20 00:00:00+00:00

======================================================================
originalConstructionDate
Original non-null: 2026
Failed to parse: 2026 success
Min: 1492-10-12 00:00:00+00:00
Max: 2025-06-01 00:00:00+00:00

======================================================================
openDate
Original non-null: 2040
Failed to parse: 2040 success
Min: 2018-01-05 00:00:00+00:00
Max: 2026-09-03 00:00:00+00:00

======================================================================
mostRecentPaymentDate
Original non-null: 1846
Failed to parse: 1846 success
Min: 1942-10-12 00:00:00+00:00
Max: 2026-09-06 00:00:00+00:00

In [ ]:
for col in date_cols:
    parsed = pd.to_datetime(df[col], errors="coerce", utc=True)

    print(f"\n{col} suspicious / failed:")
    print(df.loc[parsed.isna() & df[col].notna(), ["claim_ref", col]].head(30))

dateOfLoss suspicious / failed:
         claim_ref  dateOfLoss
40     CLM-7898726  29-09-2023
67     CLM-5746454  30-08-2023
82     CLM-6157209  10-10-2024
99     CLM-6470168  09-10-2024
144    CLM-6398916  30-09-2022
154    CLM-7011673  05-04-2025
156    CLM-5725175  23-03-2026
158    CLM-5848380  30-09-2022
165    CLM-8169782  19-05-2020
168    CLM-6916300  21-04-2025
186  CLM-7127665-R  03-09-2018
211    CLM-6799102  04-08-2019
235    CLM-6409025  21-08-2025
250    CLM-7337861  26-09-2024
318    CLM-6134163  26-09-2024
330    CLM-7980100  05-09-2019
345    CLM-5897469  14-09-2018
364    CLM-8106199  13-06-2024
379    CLM-7326132  13-09-2018
385    CLM-7159386  11-01-2020
393    CLM-7701299  06-09-2019
432    CLM-6877029  21-04-2025
456    CLM-6304365  27-03-2026
471    CLM-7648582  28-09-2022
479    CLM-8024729  16-02-2021
484    CLM-6410405  20-03-2019
489    CLM-6729784  23-09-2018
504    CLM-6134144  05-09-2020
521    CLM-5597390  20-08-2023
527    CLM-6611416  27-03-2021

originalConstructionDate suspicious / failed:
Empty DataFrame
Columns: [claim_ref, originalConstructionDate]
Index: []

openDate suspicious / failed:
Empty DataFrame
Columns: [claim_ref, openDate]
Index: []

mostRecentPaymentDate suspicious / failed:
Empty DataFrame
Columns: [claim_ref, mostRecentPaymentDate]
Index: []

In [ ]:
df_check = df.copy()

for col in [
    "dateOfLoss",
    "originalConstructionDate",
    "openDate",
    "mostRecentPaymentDate"
]:
    df_check[col + "_parsed"] = pd.to_datetime(
        df_check[col],
        errors="coerce",
        dayfirst=True,
        utc=True
    )

C:\Users\SIDDESHWAR\AppData\Local\Temp\ipykernel_35820\1963631726.py:9: UserWarning: Parsing dates in %Y-%m-%dT%H:%M:%S.%f%z format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_check[col + "_parsed"] = pd.to_datetime(
C:\Users\SIDDESHWAR\AppData\Local\Temp\ipykernel_35820\1963631726.py:9: UserWarning: Parsing dates in %Y-%m-%dT%H:%M:%S.%f%z format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_check[col + "_parsed"] = pd.to_datetime(
C:\Users\SIDDESHWAR\AppData\Local\Temp\ipykernel_35820\1963631726.py:9: UserWarning: Parsing dates in %Y-%m-%dT%H:%M:%S.%f%z format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_check[col + "_parsed"] = pd.to_datetime(

In [ ]:
bad_open = (
    df_check["openDate_parsed"].notna() &
    df_check["dateOfLoss_parsed"].notna() &
    (df_check["openDate_parsed"] < df_check["dateOfLoss_parsed"])
)

print("Open date before loss:", bad_open.sum())

print(
    df_check.loc[
        bad_open,
        ["claim_ref", "dateOfLoss", "openDate"]
    ].head(30)
)

Open date before loss: 0
Empty DataFrame
Columns: [claim_ref, dateOfLoss, openDate]
Index: []

In [ ]:
bad_payment = (
    df_check["mostRecentPaymentDate_parsed"].notna() &
    (df_check["dateOfLoss_parsed"].notna()) &
    (
        df_check["mostRecentPaymentDate_parsed"]
        < df_check["dateOfLoss_parsed"]
    )
)

print("Payment before loss:", bad_payment.sum())

print(
    df_check.loc[
        bad_payment,
        ["claim_ref", "dateOfLoss", "mostRecentPaymentDate"]
    ].head(30)
)

Payment before loss: 6
        claim_ref                dateOfLoss     mostRecentPaymentDate
8     CLM-5976757  2020-07-26T00:00:00.000Z  1942-10-12T00:00:00.000Z
134   CLM-6830799  2019-09-17T00:00:00.000Z  1942-10-12T00:00:00.000Z
199   CLM-5629942  2020-07-01T00:00:00.000Z  1942-10-12T00:00:00.000Z
501   CLM-5611558  2019-10-27T00:00:00.000Z  1942-10-12T00:00:00.000Z
723   CLM-7023722  2020-07-23T00:00:00.000Z  1942-10-12T00:00:00.000Z
1035  CLM-7769047  2020-03-24T00:00:00.000Z  1942-10-12T00:00:00.000Z

In [ ]:
bad_construction = (
    df_check["originalConstructionDate_parsed"].notna() &
    df_check["dateOfLoss_parsed"].notna() &
    (
        df_check["originalConstructionDate_parsed"]
        > df_check["dateOfLoss_parsed"]
    )
)

print("Construction after loss:", bad_construction.sum())

print(
    df_check.loc[
        bad_construction,
        ["claim_ref", "dateOfLoss", "originalConstructionDate"]
    ].head(30)
)

Construction after loss: 10
        claim_ref                dateOfLoss  originalConstructionDate
142   CLM-6338089  2024-09-20T00:00:00.000Z  2025-06-01T00:00:00.000Z
310   CLM-6153716  2022-09-28T00:00:00.000Z  2025-06-01T00:00:00.000Z
825   CLM-6454802  2020-11-09T00:00:00.000Z  2025-06-01T00:00:00.000Z
1020  CLM-6108302  2022-09-28T00:00:00.000Z  2025-06-01T00:00:00.000Z
1021  CLM-7892430  2022-09-28T00:00:00.000Z  2025-06-01T00:00:00.000Z
1186  CLM-6910176  2018-10-11T00:00:00.000Z  2025-06-01T00:00:00.000Z
1474  CLM-7453656  2021-06-18T00:00:00.000Z  2025-06-01T00:00:00.000Z
1480  CLM-6767884  2020-05-25T00:00:00.000Z  2025-06-01T00:00:00.000Z
1555  CLM-7282073  2022-09-28T00:00:00.000Z  2025-06-01T00:00:00.000Z
1878  CLM-7952766  2022-01-01T00:00:00.000Z  2025-06-01T00:00:00.000Z

# Issues found so far
1. Some rated flood zone are in smaller case and others in uppercase
2. Date format inconsistency, espesially in dateOfLoss
3. payment date < loss date - 6 rows (1942-10-12)
4. construction date > loss date - 10 rowa (2025-06-01)

In [13]:
print(
    sorted(
        df["ratedFloodZone"]
        .dropna()
        .astype(str)
        .unique()
    )
)

['A', 'A01', 'A02', 'A03', 'A04', 'A05', 'A07', 'A08', 'A09', 'A10', 'A11', 'A12', 'A13', 'A15', 'A18', 'A99', 'AE', 'AH', 'AHB', 'AO', 'AOB', 'B', 'C', 'D', 'V16', 'VE', 'X', 'a ', 'ae ', 'ah ', 'ao ', 'x ']

In [14]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

print(
    df[
        ~df["ratedFloodZone"]
        .fillna("")
        .astype(str)
        .str.upper()
        .isin([
            # don't fill this list yet
        ])
    ][["claim_ref", "ratedFloodZone"]].to_string(index=False)
)

    claim_ref ratedFloodZone
  CLM-6119947              X
  CLM-5642877             AE
  CLM-7518535             AE
  CLM-6796433             AE
  CLM-5558178             VE
  CLM-7658990              A
  CLM-6515202             AE
  CLM-7046214             AE
  CLM-5976757              X
  CLM-5813447              X
  CLM-6726350             AE
  CLM-6830121              X
  CLM-7820778             AE
  CLM-7822961              X
  CLM-5576313             AE
  CLM-7455343             AE
  CLM-8058795              X
  CLM-6596012             AE
  CLM-7062825             AE
  CLM-6053933             AE
  CLM-6223381             AE
  CLM-5637999              X
  CLM-7061589             AE
  CLM-7806166              X
  CLM-6278537              X
  CLM-8168400              A
  CLM-7130407              X
  CLM-6166678             AE
  CLM-8054536             VE
CLM-6839569-R             AE
  CLM-6701611            ae
  CLM-7934685              X
  CLM-6127266             AE
  CLM-6678927              X
  CLM-5624538             AE
  CLM-5885422             AE
  CLM-7979506              A
  CLM-7256645             AO
  CLM-6601785              A
  CLM-5804784             AE
  CLM-7898726              X
  CLM-6303511             AE
  CLM-6776458              X
  CLM-7100608             AE
  CLM-5667402             AE
  CLM-7411284             AE
  CLM-6947814             AE
  CLM-6678785             AE
  CLM-7296610             AE
  CLM-6061922             AE
  CLM-6786774             AE
  CLM-6886195             AE
  CLM-6908177             AE
  CLM-6175252             AE
  CLM-8074075              X
  CLM-6074173             AE
  CLM-6679527              X
  CLM-6993746             AE
  CLM-5619614             AE
  CLM-7239041             AE
  CLM-7283680            ae
  CLM-7179108             AE
  CLM-7736420             AE
  CLM-6420972             AE
  CLM-6470872              X
  CLM-6673494             AE
  CLM-7986783            AHB
  CLM-5746454             AE
  CLM-6212355              X
  CLM-5903387             AE
  CLM-5606042             AE
  CLM-5696937             AE
  CLM-6770988             AE
  CLM-6832577             AE
  CLM-6707573             AE
  CLM-6125069             AE
  CLM-6732637             AE
  CLM-7388317             AE
  CLM-5630616             VE
  CLM-6602663             AE
  CLM-5826796             AE
  CLM-6455117             AE
  CLM-6157209            ae
  CLM-7491850             AE
  CLM-7948788             AE
  CLM-6454676              X
  CLM-5485229             AE
  CLM-7625647             AE
  CLM-5486841             AE
  CLM-5830576             AE
  CLM-6050974             AE
  CLM-6224584              X
  CLM-5952640              A
  CLM-5630561              X
  CLM-6244844             AE
  CLM-7433300             AE
  CLM-6855178             AE
  CLM-7061363              X
  CLM-7625904             AE
  CLM-6470168             AE
  CLM-7080832             AE
  CLM-5664235             AE
  CLM-7282269              X
  CLM-6023700             AE
  CLM-7598135             AE
  CLM-5599104              X
  CLM-5971560              C
  CLM-5649534             AE
  CLM-7218663              X
  CLM-6232485             AE
  CLM-7527226            NaN
  CLM-7982462             AE
  CLM-7469967             AE
  CLM-5506490              X
  CLM-6661164             AE
  CLM-7190337              X
  CLM-6140203             AE
  CLM-5742697             AE
  CLM-8009009              X
  CLM-6494245             AE
  CLM-7965630             AE
  CLM-7789923             AE
  CLM-5572046              X
  CLM-5507307             AE
  CLM-6736067              A
  CLM-6760671             AE
  CLM-7318015             AE
  CLM-7294439              X
  CLM-7895798             AE
  CLM-7586861             AE
  CLM-7865860             AE
  CLM-6607458             AE
  CLM-5800002             AE
CLM-7433935-R             AH
  CLM-6830799              X
  CLM-7240110             AE
  CLM-6772828              X
CLM-8057769-R              X
  CLM-5685223             AE
  CLM-6836569             AE
  CLM-8118865              X
  CLM-6638126              X
  CLM-6338089             AE
  CLM-7156615             AE
  CLM-6398916             AE
  CLM-5492313              A
  CLM-6368034             AE
  CLM-6670110              X
  CLM-7860597             AE
  CLM-5533201             AE
  CLM-7813038              A
  CLM-7929868             AE
  CLM-5814535             AE
  CLM-7554054             VE
  CLM-7011673             AE
  CLM-7597385              A
  CLM-5725175             AE
  CLM-7302628              C
  CLM-5848380              A
  CLM-6010900              X
  CLM-6630633              X
  CLM-7535396             AE
  CLM-6280924             AE
  CLM-7793567             AE
  CLM-6211781             AE
  CLM-8169782             AE
  CLM-7123163             AE
  CLM-5564970              X
  CLM-6916300            ae
  CLM-6802642             AE
  CLM-6842613             AE
  CLM-5739653             AE
  CLM-6345987             AE
  CLM-8004861              X
  CLM-6304500             AE
  CLM-5950827             AE
  CLM-7035384              X
  CLM-5544627             AE
  CLM-8085372             AE
  CLM-8055635              X
  CLM-7567898            A13
  CLM-6331570              X
  CLM-6942823             AE
  CLM-6900484             AE
  CLM-7438781             AE
  CLM-5536664             AE
CLM-7127665-R              B
  CLM-8146439             AE
  CLM-6387398             AE
  CLM-7217432             AE
  CLM-5848158              X
  CLM-7945460              A
  CLM-6283800             AE
  CLM-6176189             AE
  CLM-7495589             AE
  CLM-7325864            ae
  CLM-6478754             VE
  CLM-5858191             AE
  CLM-6967195             AE
  CLM-5629942              X
  CLM-5815603              X
  CLM-6919325             AE
  CLM-5701228             AE
  CLM-6115454             AE
  CLM-7369437             AE
  CLM-7773465            A11
  CLM-6723410             AE
  CLM-6018275              A
  CLM-7685951             AE
  CLM-8049211              A
  CLM-8047506             AH
  CLM-6799102              X
  CLM-7883347             AE
  CLM-5505937             AE
  CLM-5622848              C
  CLM-7838945             AE
  CLM-5668794             AE
  CLM-6737927             AE
  CLM-7380330             AE
  CLM-7433935             AH
  CLM-6391803             AE
  CLM-7510621            NaN
  CLM-7601909             AE
  CLM-7798528             AE
  CLM-6790325             AE
  CLM-6264830             AE
  CLM-7691505             AE
CLM-8140690-R              X
  CLM-7472079             AE
  CLM-7764559             AE
  CLM-7529259             VE
  CLM-7526819             VE
  CLM-7950912             AE
  CLM-5757281             VE
  CLM-6613774              X
  CLM-6409025             AE
  CLM-7166295             AE
  CLM-6878624             AE
  CLM-8134770            A05
  CLM-7975730            A08
  CLM-7333444             AE
  CLM-7899950             VE
  CLM-7916539             AE
  CLM-7356352             AE
  CLM-5487327             AE
  CLM-6129707              X
  CLM-6696494             AE
  CLM-5889989              X
  CLM-6990246             AE
  CLM-6830915             AE
  CLM-7337861             AE
  CLM-7488272             AE
  CLM-6476053             AE
  CLM-7610279              A
  CLM-5614165             AE
  CLM-5919560             AE
  CLM-5818165             AE
  CLM-6488458             AE
  CLM-5635534             AE
  CLM-6329985             AE
  CLM-7369217              X
  CLM-5460824              X
  CLM-5712065            ae
  CLM-6973891             AE
  CLM-7248573             AE
  CLM-6461306             AE
  CLM-8002272             AE
  CLM-5686726             AE
  CLM-7650338             AE
  CLM-7201693             AE
  CLM-5493394              X
  CLM-6284141             AE
  CLM-7981910              A
  CLM-5904748             AE
  CLM-7711202             AE
  CLM-5802288             AE
  CLM-7120869             AE
  CLM-7689439              B
  CLM-7073768             AE
  CLM-6276464              A
  CLM-6906720             AE
  CLM-7833548              X
  CLM-8067567             AE
  CLM-7899954             AE
  CLM-5563524             AE
  CLM-7796764             AE
  CLM-7303457             AE
  CLM-7415021             x
  CLM-5622724             AE
  CLM-6661535             AE
  CLM-6370932             AE
  CLM-7575077              A
  CLM-7221716             AE
  CLM-7073345              X
  CLM-7780398             AE
  CLM-6871876             AE
  CLM-7544870             AH
  CLM-6676707              X
  CLM-8166345             AE
CLM-6521778-R             AE
  CLM-7159799             AE
  CLM-7290876             AE
  CLM-7880206            A15
  CLM-7330184             AE
  CLM-7889579              X
  CLM-7864740              X
  CLM-5537577            ae
  CLM-7344442              A
  CLM-5770781             AE
  CLM-6824350              X
  CLM-6153716             AE
  CLM-5868777              X
  CLM-6053137             AE
  CLM-5972139             x
CLM-7124335-R             AE
  CLM-7912033             AE
  CLM-6389310              X
  CLM-6348489              X
  CLM-6134163             AE
  CLM-7308902              X
  CLM-6476514              X
  CLM-7813656             AE
  CLM-5965062              X
  CLM-6116731             AE
  CLM-8103436              A
  CLM-6717558              A
  CLM-5980121             AE
  CLM-7035964              X
  CLM-7701789             AE
  CLM-5637366             AE
  CLM-7980100              B
  CLM-7124520              X
  CLM-5720130             AE
  CLM-6728305             AE
  CLM-5596501             AE
  CLM-5604085              X
  CLM-6686763              A
  CLM-7676524             AE
  CLM-7156599             AE
  CLM-7848168              X
  CLM-7621478             AE
  CLM-5624245             AE
  CLM-6086117              A
  CLM-7660368             AE
  CLM-6421862             AE
  CLM-5897469              X
  CLM-7577485              A
  CLM-7721208            A09
  CLM-6421419              X
  CLM-7593964             AE
  CLM-6277986              X
  CLM-6811528             AE
  CLM-7806898             AE
  CLM-6123171             AE
  CLM-7904428             AO
  CLM-7700093             AE
  CLM-6519081              A
  CLM-6875008             AE
  CLM-7943261             AE
  CLM-6491381             AE
  CLM-6378951              A
  CLM-7960288              X
  CLM-5933394             AE
  CLM-7338211             AE
  CLM-8106199             AE
  CLM-5792810             VE
  CLM-7651487             AE
  CLM-6292388             AE
  CLM-7823368              X
  CLM-7805331             AE
  CLM-7522505             AO
  CLM-6005852             AE
  CLM-6280777              X
  CLM-7279505             AE
  CLM-7230190             VE
  CLM-6950039            A18
  CLM-6621812             AE
  CLM-7306078             AE
CLM-6229538-R            A08
  CLM-7326132             AE
  CLM-6486840             AE
  CLM-6130249             AE
  CLM-6880537              X
  CLM-7797417             AE
  CLM-6550216             AE
  CLM-7159386              C
  CLM-6222596             VE
  CLM-5805691             AE
  CLM-7398935            ae
  CLM-7802082             AE
  CLM-8006965              A
  CLM-6806019             AE
  CLM-6350231             AE
  CLM-7701299             AE
  CLM-7810700             AE
  CLM-7543098              A
  CLM-5604093             AE
  CLM-7458322             AE
  CLM-6893050             AE
  CLM-5803112             AE
  CLM-7879402             AE
  CLM-7583380             AE
  CLM-7260716             AE
  CLM-8109648              C
  CLM-6566778             AE
  CLM-6686277             AE
  CLM-5849050             AE
  CLM-6841047             AE
  CLM-8002436             AE
  CLM-6246501             AE
  CLM-6558803             AE
  CLM-7937758             AE
  CLM-5946009              A
  CLM-7686747              X
  CLM-5543326             AE
  CLM-5456412              X
  CLM-6923206             AE
  CLM-8082188             AE
  CLM-7475750              X
  CLM-6207903             AE
  CLM-7383028              X
  CLM-6043923              X
  CLM-5972314             VE
  CLM-5532848              X
  CLM-5801880            A10
  CLM-8110944             AE
  CLM-7675423             AE
  CLM-6839351             AE
  CLM-7773144             AE
  CLM-8099259             AE
  CLM-6597136              X
  CLM-5843795              X
  CLM-6877029             AE
  CLM-5818171             AE
  CLM-7371450             AE
  CLM-6967557             AE
  CLM-7099591             AE
  CLM-6159923             AE
  CLM-7971592             AE
  CLM-6227390             AE
  CLM-7308661             AE
  CLM-7239705             AE
  CLM-6655681             AE
  CLM-6631650             AE
  CLM-5659332             AE
  CLM-6515204             AE
  CLM-6171406              X
  CLM-6788159              A
  CLM-7842108             AE
  CLM-6039630              X
  CLM-7302971              A
  CLM-7604452             AE
  CLM-6806081             AE
  CLM-8124449             AE
  CLM-5638771              X
  CLM-7451577             AE
  CLM-6304365             AE
  CLM-5781988             AE
  CLM-7329332             AE
  CLM-7998616             AE
  CLM-7124448              X
  CLM-6628309             AE
  CLM-7173174             AE
  CLM-6140166              X
  CLM-6017770              X
  CLM-7827065             AO
  CLM-6507600              X
  CLM-7930958             AE
  CLM-7610551             AE
  CLM-6872463             AE
  CLM-5603972              X
  CLM-7648582             AE
  CLM-5987143              X
  CLM-6421442             AE
  CLM-7121241             VE
  CLM-6586090             AE
  CLM-6196000            A07
  CLM-7133497              X
  CLM-8050834             AE
  CLM-8024729              A
  CLM-8115773             AE
  CLM-6842414             VE
  CLM-5471799              X
  CLM-7153069            A01
  CLM-6410405             AE
  CLM-7249306             AE
  CLM-5726698              X
  CLM-5904483             AE
  CLM-7024661             AE
  CLM-6729784             AE
  CLM-6658432              A
  CLM-8057247              X
  CLM-6053106              X
  CLM-5675889             AO
  CLM-6771568              X
  CLM-6708549             AE
  CLM-7100502              X
  CLM-7580654              X
  CLM-7536327             AE
  CLM-5539987              X
  CLM-6107264             AE
  CLM-5611558             AE
  CLM-5507360             AE
  CLM-6986881             AE
  CLM-6134144              A
  CLM-5848215            ae
  CLM-7237151              X
  CLM-5470793             AE
  CLM-7532726              X
  CLM-5654480              A
  CLM-6445210              X
  CLM-7853885             VE
  CLM-7433053             AE
  CLM-5925198             AE
  CLM-6517084              X
  CLM-7338746              X
  CLM-8013899             AE
  CLM-5684472              X
  CLM-7344439             AE
  CLM-6563228             AE
  CLM-7579975             AE
  CLM-5597390              X
  CLM-5768742             AE
  CLM-7827414             AE
  CLM-6536144              A
  CLM-6028898             AE
  CLM-6946505             AE
  CLM-6611416              X
  CLM-8138650              X
CLM-8041087-R              A
  CLM-6199438              X
  CLM-7280291              X
  CLM-5559679             AE
  CLM-8072907             AE
  CLM-7164176             AE
  CLM-6925981             AE
  CLM-6182683             AE
  CLM-6980395              X
  CLM-8099283             AE
  CLM-6323738             AE
  CLM-5693483              A
  CLM-7084140             AE
  CLM-6785152             AE
  CLM-7905386              X
  CLM-6436768              X
  CLM-5835196             AE
  CLM-7020108             AE
  CLM-6292038              A
  CLM-8068161             AE
  CLM-7980642             VE
  CLM-6315338             AE
  CLM-6900826             AE
  CLM-7174149             AE
  CLM-6836135              X
  CLM-5550642             AE
  CLM-7379739              X
  CLM-8057769              X
  CLM-6867609            ae
  CLM-7671775             AE
  CLM-7422438              X
  CLM-5696202              X
  CLM-6120003            A02
  CLM-6165167              C
  CLM-7072820            ae
  CLM-6002424             AE
  CLM-5639566             AE
  CLM-6498588              X
  CLM-7954151            ae
  CLM-5955654             AE
  CLM-6350855              C
  CLM-5699834              A
  CLM-7256466              X
  CLM-7732496             AE
  CLM-6231791             AE
  CLM-6708555             AE
  CLM-6143335             AE
  CLM-6218484              A
  CLM-5754529             AE
  CLM-5949040             AE
  CLM-6325427             AE
CLM-8109648-R              C
  CLM-5452173             AE
  CLM-8100313             AE
  CLM-6689379             AE
  CLM-6218964             AE
  CLM-6645627              X
  CLM-8004040             x
  CLM-7390466             AE
  CLM-6450562             AE
  CLM-6798980             AE
  CLM-7306056              X
  CLM-6205918              X
  CLM-7020358             AE
  CLM-7824974              X
  CLM-7608415              X
  CLM-7721750             AE
  CLM-7716214             AE
  CLM-6164189             AE
  CLM-6281298             VE
  CLM-7317886             AE
  CLM-6260104             AE
  CLM-7199889             AE
  CLM-7710883              C
  CLM-7981299             AE
  CLM-7102440             AE
  CLM-6819541             AE
  CLM-5888360             AE
  CLM-6015489              X
  CLM-5568313             AE
  CLM-6992917             AE
  CLM-6524418             AE
  CLM-7529419             AE
  CLM-7859081             AE
  CLM-7313820              X
  CLM-7104715            ae
  CLM-8041105             AE
  CLM-7535267              X
  CLM-8098777              B
  CLM-7334270             AE
  CLM-5531458             AE
  CLM-8085210             AE
  CLM-7691235              X
  CLM-5571044              X
  CLM-8016520             AE
  CLM-6081847             AE
  CLM-5726364             AE
  CLM-6836238             AE
  CLM-5490661             AE
  CLM-6116476             AE
  CLM-6254003             AE
  CLM-5791066             AE
  CLM-7408518             AO
  CLM-7893133            ae
  CLM-6136805             AE
  CLM-6774628              A
  CLM-6977805             AE
  CLM-6079388              X
  CLM-7152266             AE
  CLM-6248538             AH
  CLM-7374210             AO
  CLM-7039297              X
  CLM-6267367             AE
  CLM-7318586              A
  CLM-7086059              A
  CLM-7550880              A
  CLM-7009129             AE
  CLM-7498913              A
  CLM-6840483             AE
  CLM-6701859            ae
  CLM-6834021             AH
  CLM-7132163             AE
  CLM-5651249             AE
  CLM-6550970              X
  CLM-5619471             AE
  CLM-6811071             AE
  CLM-7955925              X
  CLM-6159254             AE
  CLM-7599577              X
  CLM-5899634             AE
  CLM-5662806             AE
  CLM-6969935             AE
  CLM-6584078             AE
  CLM-7791463             AE
  CLM-7158632             AE
  CLM-7468484             AE
  CLM-5632217             AE
  CLM-5944209            ae
  CLM-5733300             AE
  CLM-6575284              X
  CLM-7138895              X
  CLM-7279060              X
  CLM-5818266             x
  CLM-5893075              X
  CLM-6307412             AE
  CLM-7566597             AE
  CLM-7806776              X
  CLM-6900261             AE
  CLM-6414083             AE
  CLM-7438811             AE
  CLM-5630816             AE
  CLM-6812170             AE
  CLM-7266323             VE
  CLM-6272892              X
  CLM-7429690             AE
  CLM-6210612             AE
  CLM-6428997             AE
  CLM-6707329             AE
  CLM-7222084             AE
  CLM-6825692             AE

# Clean 1
Converted all lower case to upper case in ratedFloodZone

In [15]:
df["ratedFloodZone"] = (
    df["ratedFloodZone"]
    .str.strip()
    .str.upper()
)

In [16]:
suspicious_zones = ["AHB", "AOB"]

print(
    df[df["ratedFloodZone"].isin(suspicious_zones)][
        ["claim_ref", "source_system", "state",
         "reportedZipCode", "ratedFloodZone"]
    ]
)

       claim_ref source_system state reportedZipCode ratedFloodZone
66   CLM-7986783          core    TX           78503            AHB
879  CLM-7990756          core    CA           93065            AOB

In [17]:
print(
    df["ratedFloodZone"]
    .value_counts(dropna=False)
    .sort_index()
)

ratedFloodZone
A        96
A01       2
A02       1
A03       1
A04       3
A05       2
A07       2
A08       6
A09       3
A10       4
A11       1
A12       2
A13       4
A15       2
A18       1
A99       5
AE     1295
AH       33
AHB       1
AO       21
AOB       1
B        12
C        26
D         1
V16       1
VE       66
X       443
NaN       5
Name: count, dtype: int64

In [18]:
parsed_loss = pd.to_datetime(
    df["dateOfLoss"],
    errors="coerce",
    utc=True
)

failed = parsed_loss.isna()

print(
    df.loc[
        failed,
        ["claim_ref", "source_system", "dateOfLoss", "yearOfLoss"]
    ].head(20)
)

print("\nSource distribution:")
print(df.loc[failed, "source_system"].value_counts())

         claim_ref source_system  dateOfLoss  yearOfLoss
40     CLM-7898726    legacy_bdx  29-09-2023        2023
67     CLM-5746454    legacy_bdx  30-08-2023        2023
82     CLM-6157209    legacy_bdx  10-10-2024        2024
99     CLM-6470168    legacy_bdx  09-10-2024        2024
144    CLM-6398916    legacy_bdx  30-09-2022        2022
154    CLM-7011673    legacy_bdx  05-04-2025        2025
156    CLM-5725175    legacy_bdx  23-03-2026        2026
158    CLM-5848380    legacy_bdx  30-09-2022        2022
165    CLM-8169782    legacy_bdx  19-05-2020        2020
168    CLM-6916300    legacy_bdx  21-04-2025        2025
186  CLM-7127665-R    legacy_bdx  03-09-2018        2018
211    CLM-6799102    legacy_bdx  04-08-2019        2019
235    CLM-6409025    legacy_bdx  21-08-2025        2025
250    CLM-7337861    legacy_bdx  26-09-2024        2024
318    CLM-6134163    legacy_bdx  26-09-2024        2024
330    CLM-7980100    legacy_bdx  05-09-2019        2019
345    CLM-5897469    legacy_bdx  14-09-2018        2018
364    CLM-8106199    legacy_bdx  13-06-2024        2024
379    CLM-7326132    legacy_bdx  13-09-2018        2018
385    CLM-7159386    legacy_bdx  11-01-2020        2020

Source distribution:
source_system
legacy_bdx    123
Name: count, dtype: int64

# Clean 2

Because the exact same old date appears repeatedly and creates the violation, this is strong evidence that 1942-10-12 is a placeholder/default rather than a genuine payment date.

So I decided to change them because they it is pracitcally not possible so i set them to Nan.

In [19]:
result = df[
    pd.to_datetime(df["mostRecentPaymentDate"], errors="coerce").dt.date
    == pd.Timestamp("1942-10-12").date()
]

print(
    result[
        [
            "claim_ref",
            "dateOfLoss",
            "mostRecentPaymentDate",
            "amountPaidOnBuildingClaim",
            "amountPaidOnContentsClaim",
            "netBuildingPaymentAmount",
            "nonPaymentReasonBuilding",
            "source_system"
        ]
    ].to_string(index=False)
)

  claim_ref               dateOfLoss    mostRecentPaymentDate  amountPaidOnBuildingClaim  amountPaidOnContentsClaim  netBuildingPaymentAmount  nonPaymentReasonBuilding source_system
CLM-5976757 2020-07-26T00:00:00.000Z 1942-10-12T00:00:00.000Z                        0.0                        0.0                       0.0                       1.0          core
CLM-6830799 2019-09-17T00:00:00.000Z 1942-10-12T00:00:00.000Z                        0.0                        0.0                       0.0                       1.0          core
CLM-5629942 2020-07-01T00:00:00.000Z 1942-10-12T00:00:00.000Z                        0.0                        0.0                       0.0                       1.0          core
CLM-5611558 2019-10-27T00:00:00.000Z 1942-10-12T00:00:00.000Z                        0.0                        0.0                       0.0                      99.0          core
CLM-7023722 2020-07-23T00:00:00.000Z 1942-10-12T00:00:00.000Z                        0.0                        0.0                       0.0                      97.0          core
CLM-7769047 2020-03-24T00:00:00.000Z 1942-10-12T00:00:00.000Z                        0.0                        0.0                       0.0                      97.0          core

In [20]:
df_clean = df.copy()

In [21]:
import pandas as pd

# Work with the original strings
raw_loss = df_clean["dateOfLoss"].astype("string").str.strip()

# Create an empty datetime Series with UTC timezone
parsed_loss = pd.Series(
    pd.NaT,
    index=df_clean.index,
    dtype="datetime64[ns, UTC]"
)

# Identify the two formats
iso_mask = raw_loss.str.match(r"^\d{4}-\d{2}-\d{2}T")
legacy_mask = raw_loss.str.match(r"^\d{2}/\d{2}/\d{4}$")

# Parse ISO dates
parsed_loss.loc[iso_mask] = pd.to_datetime(
    raw_loss.loc[iso_mask],
    format="%Y-%m-%dT%H:%M:%S.%fZ",
    errors="coerce",
    utc=True
)

# Parse legacy DD/MM/YYYY dates
parsed_loss.loc[legacy_mask] = pd.to_datetime(
    raw_loss.loc[legacy_mask],
    format="%d/%m/%Y",
    errors="coerce",
    utc=True
)

# Replace the original column
df_clean["dateOfLoss"] = parsed_loss

In [22]:
for col in [
    "originalConstructionDate",
    "openDate",
    "mostRecentPaymentDate"
]:
    df_clean[col] = pd.to_datetime(
        df_clean[col],
        errors="coerce",
        utc=True
    )

In [23]:
date_cols = [
    "dateOfLoss",
    "originalConstructionDate",
    "openDate",
    "mostRecentPaymentDate"
]

for col in date_cols:
    print(
        col,
        "dtype =", df_clean[col].dtype,
        "| missing =", df_clean[col].isna().sum()
    )

dateOfLoss dtype = datetime64[ns, UTC] | missing = 123
originalConstructionDate dtype = datetime64[us, UTC] | missing = 14
openDate dtype = datetime64[us, UTC] | missing = 0
mostRecentPaymentDate dtype = datetime64[us, UTC] | missing = 194

In [24]:
mask = df_clean["mostRecentPaymentDate"] == pd.Timestamp(
    "1942-10-12",
    tz="UTC"
)

df_clean.loc[mask, "mostRecentPaymentDate"] = pd.NaT

In [25]:
print(
    "Remaining 1942-10-12:",
    (df_clean["mostRecentPaymentDate"] ==
     pd.Timestamp("1942-10-12", tz="UTC")).sum()
)

Remaining 1942-10-12: 0

In [26]:
mask = df_clean["originalConstructionDate"] == pd.Timestamp(
    "2025-06-01",
    tz="UTC"
)

df_clean.loc[mask, "originalConstructionDate"] = pd.NaT

In [27]:
print(
    "Payment before loss:",
    (df_clean["mostRecentPaymentDate"] <
     df_clean["dateOfLoss"]).sum()
)

print(
    "Construction after loss:",
    (df_clean["originalConstructionDate"] >
     df_clean["dateOfLoss"]).sum()
)

Payment before loss: 0
Construction after loss: 0

In [28]:
numeric_cols = [
    "countyCode",
    "latitude",
    "longitude",
    "occupancyType",
    "numberOfFloorsInTheInsuredBuilding",
    "elevatedBuildingIndicator",
    "primaryResidenceIndicator",
    "totalBuildingInsuranceCoverage",
    "totalContentsInsuranceCoverage",
    "buildingPropertyValue",
    "buildingReplacementCost",
    "buildingDamageAmount",
    "contentsDamageAmount",
    "waterDepth",
    "floodWaterDuration",
    "amountPaidOnBuildingClaim",
    "amountPaidOnContentsClaim",
    "netBuildingPaymentAmount",
    "nonPaymentReasonBuilding"
]

for col in numeric_cols:
    print(f"\n--- {col} ---")
    print("min:", df_clean[col].min())
    print("max:", df_clean[col].max())
    print("negative:", (df_clean[col] < 0).sum())
    print("zero:", (df_clean[col] == 0).sum())

--- countyCode ---
min: 1003.0
max: 72061.0
negative: 0
zero: 0

--- latitude ---
min: -93.5
max: 49.0
negative: 8
zero: 0

--- longitude ---
min: -159.5
max: 41.6
negative: 2018
zero: 0

--- occupancyType ---
min: 1
max: 18
negative: 0
zero: 0

--- numberOfFloorsInTheInsuredBuilding ---
min: 1.0
max: 5.0
negative: 0
zero: 0

--- elevatedBuildingIndicator ---
min: 0
max: 1
negative: 0
zero: 1579

--- primaryResidenceIndicator ---
min: 0
max: 1
negative: 0
zero: 659

--- totalBuildingInsuranceCoverage ---
min: 14.0
max: 20165000.0
negative: 0
zero: 0

--- totalContentsInsuranceCoverage ---
min: 0.0
max: 500000.0
negative: 0
zero: 627

--- buildingPropertyValue ---
min: 0.0
max: 107805333.0
negative: 0
zero: 163

--- buildingReplacementCost ---
min: 0.0
max: 155771643.0
negative: 0
zero: 163

--- buildingDamageAmount ---
min: 0.0
max: 3085581.0
negative: 0
zero: 164

--- contentsDamageAmount ---
min: 0.0
max: 1490364.0
negative: 0
zero: 404

--- waterDepth ---
min: -99.0
max: 162.0
negative: 110
zero: 677

--- floodWaterDuration ---
min: 0.0
max: 195.0
negative: 0
zero: 420

--- amountPaidOnBuildingClaim ---
min: -5.0
max: 34912215.45
negative: 1
zero: 222

--- amountPaidOnContentsClaim ---
min: -1.0
max: 500000.0
negative: 1
zero: 1221

--- netBuildingPaymentAmount ---
min: -5.0
max: 3447017.17
negative: 1
zero: 418

--- nonPaymentReasonBuilding ---
min: 1.0
max: 99.0
negative: 0
zero: 0

In [29]:
# Building damage greater than property value
check1 = df_clean[
    df_clean["buildingDamageAmount"] >
    df_clean["buildingPropertyValue"]
]

print("Damage > Property Value:", len(check1))

Damage > Property Value: 77

In [30]:
# Building damage greater than replacement cost
check2 = df_clean[
    df_clean["buildingDamageAmount"] >
    df_clean["buildingReplacementCost"]
]

print("Damage > Replacement Cost:", len(check2))

Damage > Replacement Cost: 73

In [31]:
# Building payment greater than building damage
check3 = df_clean[
    df_clean["amountPaidOnBuildingClaim"] >
    df_clean["buildingDamageAmount"]
]

print("Payment > Building Damage:", len(check3))

Payment > Building Damage: 416

In [32]:
# Building payment greater than building insurance coverage
check4 = df_clean[
    df_clean["amountPaidOnBuildingClaim"] >
    df_clean["totalBuildingInsuranceCoverage"]
]

print("Payment > Building Coverage:", len(check4))

Payment > Building Coverage: 21

In [33]:
check3[
    [
        "claim_ref",
        "buildingDamageAmount",
        "amountPaidOnBuildingClaim",
        "totalBuildingInsuranceCoverage",
        "netBuildingPaymentAmount",
        "source_system"
    ]
].head(20)

,claim_ref,buildingDamageAmount,amountPaidOnBuildingClaim,totalBuildingInsuranceCoverage,netBuildingPaymentAmount,source_system
5,CLM-7658990,27337.0,32195.94,144000.0,32195.94,core
11,CLM-6830121,6860.0,7841.52,250000.0,7841.52,core
13,CLM-7822961,59343.0,69572.93,250000.0,69572.93,core
24,CLM-6278537,63571.0,70563.40,250000.0,70563.40,core
27,CLM-6166678,12021.0,12592.37,250000.0,12592.37,core
43,CLM-7100608,122175.0,129784.55,250000.0,129784.55,core
45,CLM-7411284,15087.0,17023.65,250000.0,17023.65,core
50,CLM-6786774,22779.0,23893.23,250000.0,23893.23,core
60,CLM-7283680,155154.0,170596.62,250000.0,170596.62,core
88,CLM-5486841,28535.0,44000.00,22000.0,44000.00,core
89,CLM-5830576,15538.0,16692.06,100000.0,16692.06,core
100,CLM-7080832,3085581.0,3447017.17,13000000.0,3447017.17,core
101,CLM-5664235,132804.0,136041.79,250000.0,136041.79,core
107,CLM-5649534,106771.0,115669.81,250000.0,115669.81,core
112,CLM-7469967,81600.0,94140.93,250000.0,94140.93,core
114,CLM-6661164,109189.0,119921.26,250000.0,119921.26,core
117,CLM-5742697,147665.0,155017.86,250000.0,155017.86,core
120,CLM-7965630,132756.0,148580.55,250000.0,148580.55,core
125,CLM-6760671,71160.0,87390.91,220000.0,87390.91,core
128,CLM-7895798,23736.0,24283.11,1500000.0,24283.11,core

## Issue
Found water depth and few claims as negative. 

Planned to replace negative claims with nan as it is not possible to have negative claims.

Retained water depth because I didn't have sufficient schema/domain evidence to prove they were invalid.

Set only the invalid latitude values to NaN as they were below -90.

In [34]:
df_clean.loc[df_clean["waterDepth"] < 0, "waterDepth"].value_counts()

waterDepth
-7.0     22
-1.0     16
-5.0     13
-8.0     10
-2.0     10
-6.0      9
-3.0      8
-9.0      8
-4.0      5
-99.0     1
-12.0     1
-10.0     1
-42.0     1
-89.0     1
-93.0     1
-57.0     1
-67.0     1
-20.0     1
Name: count, dtype: int64

In [35]:
df_clean[
    (df_clean["amountPaidOnBuildingClaim"] < 0) |
    (df_clean["amountPaidOnContentsClaim"] < 0) |
    (df_clean["netBuildingPaymentAmount"] < 0)
][[
    "claim_ref",
    "amountPaidOnBuildingClaim",
    "amountPaidOnContentsClaim",
    "netBuildingPaymentAmount",
    "nonPaymentReasonBuilding",
    "source_system"
]]

,claim_ref,amountPaidOnBuildingClaim,amountPaidOnContentsClaim,netBuildingPaymentAmount,nonPaymentReasonBuilding,source_system
330,CLM-7980100,-5.0,-1.0,-5.0,98.0,legacy_bdx

In [36]:
df_clean[
    (df_clean["latitude"] < -90) |
    (df_clean["latitude"] > 90)
][[
    "claim_ref", "latitude", "longitude", "state", "reportedZipCode"
]]

        claim_ref  latitude  longitude state reportedZipCode
582   CLM-8100313     -93.5       41.6    IA           50317
1064  CLM-7961163     -91.0       30.3    LA           70769
1855  CLM-6284078     -90.5       30.1    LA           70068

In [37]:
print("NEGATIVE WATER DEPTH")
print(df_clean.loc[df_clean["waterDepth"] < 0, "waterDepth"].value_counts())

print("\nNEGATIVE PAYMENTS")
print(df_clean[
    (df_clean["amountPaidOnBuildingClaim"] < 0) |
    (df_clean["amountPaidOnContentsClaim"] < 0) |
    (df_clean["netBuildingPaymentAmount"] < 0)
][[
    "claim_ref",
    "amountPaidOnBuildingClaim",
    "amountPaidOnContentsClaim",
    "netBuildingPaymentAmount",
    "nonPaymentReasonBuilding",
    "source_system"
]])

print("\nINVALID LATITUDE")
print(df_clean[
    (df_clean["latitude"] < -90) |
    (df_clean["latitude"] > 90)
][[
    "claim_ref", "latitude", "longitude",
    "state", "reportedZipCode", "source_system"
]])

print("\nPAYMENT > COVERAGE")
print(df_clean[
    df_clean["amountPaidOnBuildingClaim"] >
    df_clean["totalBuildingInsuranceCoverage"]
][[
    "claim_ref",
    "amountPaidOnBuildingClaim",
    "totalBuildingInsuranceCoverage",
    "buildingDamageAmount",
    "netBuildingPaymentAmount",
    "source_system"
]])

NEGATIVE WATER DEPTH
waterDepth
-7.0     22
-1.0     16
-5.0     13
-8.0     10
-2.0     10
-6.0      9
-3.0      8
-9.0      8
-4.0      5
-99.0     1
-12.0     1
-10.0     1
-42.0     1
-89.0     1
-93.0     1
-57.0     1
-67.0     1
-20.0     1
Name: count, dtype: int64

NEGATIVE PAYMENTS
       claim_ref  amountPaidOnBuildingClaim  amountPaidOnContentsClaim  \
330  CLM-7980100                       -5.0                       -1.0

     netBuildingPaymentAmount  nonPaymentReasonBuilding source_system
330                      -5.0                      98.0    legacy_bdx

INVALID LATITUDE
        claim_ref  latitude  longitude state reportedZipCode source_system
582   CLM-8100313     -93.5       41.6    IA           50317          core
1064  CLM-7961163     -91.0       30.3    LA           70769          core
1855  CLM-6284078     -90.5       30.1    LA           70068          core

PAYMENT > COVERAGE
        claim_ref  amountPaidOnBuildingClaim  totalBuildingInsuranceCoverage  \
88    CLM-5486841                   44000.00                         22000.0
138   CLM-5685223                  601320.57                        250000.0
177   CLM-5544627                34912215.45                      15000000.0
422   CLM-5972314                  310170.62                        267000.0
452   CLM-6806081                   25907.76                         22000.0
482   CLM-5471799                  471108.86                        250000.0
525   CLM-6028898                  498978.44                        250000.0
547   CLM-6292038                  490633.32                        167000.0
655   CLM-7955925                   29512.64                         20000.0
727   CLM-6887750                  481263.76                        250000.0
883   CLM-7099418                  373296.15                        250000.0
1110  CLM-5988109                  494190.20                        200000.0
1180  CLM-6825487                  107380.47                         98000.0
1240  CLM-7798283                  417022.49                        250000.0
1290  CLM-6925211                  950091.17                        500000.0
1354  CLM-5634083                  367916.84                        250000.0
1485  CLM-7489924                  368216.45                        250000.0
1554  CLM-8078474                  501394.56                        199000.0
1669  CLM-5665942                  202152.27                         74000.0
1976  CLM-7453133                  416710.99                        250000.0
2016  CLM-7535505                   15261.00                          9300.0

      buildingDamageAmount  netBuildingPaymentAmount source_system
88                 28535.0                  44000.00          core
138                99471.0                  94471.19          core
177                45824.0                  44586.42          core
422               270700.0                 310170.62          core
452                27408.0                  25907.76          core
482                53180.0                  55251.15          core
525               248856.0                 250000.00          core
547                13721.0                   5821.32          core
655                31512.0                  29512.64          core
727                    NaN                      0.00          core
883                    NaN                      0.00          core
1110               83439.0                  85213.31          core
1180              109380.0                 107380.47          core
1240                   0.0                      0.00          core
1290                3674.0                   2423.80          core
1354              231133.0                 221133.05          core
1485                8871.0                   7622.18          core
1554               15623.0                   7124.44          core
1669                7319.0                   6319.53          core
1976                   0.0                      0.00          core
2016               16761.0                  15261.00          core

In [38]:
df_clean[
    df_clean["amountPaidOnBuildingClaim"].notna() &
    df_clean["netBuildingPaymentAmount"].notna()
].assign(
    difference=lambda x:
        x["amountPaidOnBuildingClaim"] -
        x["netBuildingPaymentAmount"]
)[[
    "claim_ref",
    "amountPaidOnBuildingClaim",
    "netBuildingPaymentAmount",
    "difference",
    "source_system"
]].sort_values(
    "difference",
    ascending=False
).head(20)

,claim_ref,amountPaidOnBuildingClaim,netBuildingPaymentAmount,difference,source_system
177,CLM-5544627,34912215.45,44586.42,34867629.03,core
1290,CLM-6925211,950091.17,2423.80,947667.37,core
138,CLM-5685223,601320.57,94471.19,506849.38,core
1554,CLM-8078474,501394.56,7124.44,494270.12,core
547,CLM-6292038,490633.32,5821.32,484812.00,core
727,CLM-6887750,481263.76,0.00,481263.76,core
1240,CLM-7798283,417022.49,0.00,417022.49,core
1976,CLM-7453133,416710.99,0.00,416710.99,core
482,CLM-5471799,471108.86,55251.15,415857.71,core
1110,CLM-5988109,494190.20,85213.31,408976.89,core
883,CLM-7099418,373296.15,0.00,373296.15,core
1485,CLM-7489924,368216.45,7622.18,360594.27,core
525,CLM-6028898,498978.44,250000.00,248978.44,core
1669,CLM-5665942,202152.27,6319.53,195832.74,core
1354,CLM-5634083,367916.84,221133.05,146783.79,core
6,CLM-6515202,61000.00,61000.00,0.00,core
2023,CLM-6983024,99031.13,99031.13,0.00,core
2024,CLM-6701024,49664.78,49664.78,0.00,core
2025,CLM-5491980,34592.44,34592.44,0.00,core
2026,CLM-6833813,10187.41,10187.41,0.00,core

In [39]:
negative_water = df_clean[df_clean["waterDepth"] < 0]

print(
    negative_water[
        [
            "claim_ref",
            "waterDepth",
            "floodWaterDuration",
            "floodEvent",
            "causeOfDamage",
            "source_system"
        ]
    ].to_string(index=False)
)

    claim_ref  waterDepth  floodWaterDuration                       floodEvent causeOfDamage source_system
  CLM-7898726        -7.0                 NaN Late-September New York Flooding             4    legacy_bdx
  CLM-6776458        -8.0                 NaN                              NaN             4          core
  CLM-8074075        -7.0                 NaN                              NaN             4          core
  CLM-7218663        -3.0                 NaN                              NaN             4          core
  CLM-6494245        -2.0                 NaN                    Hurricane Ida             2          core
  CLM-5800002        -5.0                 NaN                 Hurricane Milton             1          core
  CLM-7240110        -7.0                 NaN                    Hurricane Ida             4          core
  CLM-8118865        -3.0                 NaN                    Hurricane Ida             4          core
  CLM-5492313        -7.0                 NaN                              NaN             4          core
  CLM-5739653        -9.0                 NaN                              NaN             2          core
  CLM-5629942        -7.0                 NaN                              NaN             0          core
  CLM-5505937        -5.0                 NaN                              NaN             2          core
  CLM-7601909        -7.0                 0.0                              NaN             4          core
  CLM-7166295       -99.0                 NaN                              NaN             2          core
  CLM-7899950       -12.0                 NaN                 Hurricane Helene             1          core
  CLM-5889989        -4.0                 NaN                    Hurricane Ida             4          core
  CLM-5460824        -7.0                 NaN        Vermont/New York Flooding             4          core
  CLM-6134163        -2.0                 NaN                 Hurricane Helene             1    legacy_bdx
  CLM-6123171       -10.0                 NaN                              NaN             2          core
  CLM-6550216       -42.0                 NaN                 Hurricane Helene             1          core
  CLM-7159386        -1.0                 NaN                              NaN             1    legacy_bdx
  CLM-6566778        -1.0                 NaN                              NaN             2          core
  CLM-7937758        -8.0                 NaN                    Hurricane Ida             2          core
  CLM-5456412        -9.0                 0.0                              NaN             4          core
  CLM-7475750        -6.0                 0.0                              NaN             4          core
  CLM-5532848        -1.0                 0.0               Hurricane Florence             2          core
  CLM-8124449        -1.0                 NaN                 Hurricane Helene             4          core
  CLM-7930958        -3.0                 NaN                    Hurricane Ian             1          core
  CLM-8057247        -5.0                 0.0                              NaN             4          core
  CLM-6771568        -7.0                 NaN Late-September New York Flooding             4          core
  CLM-6708549        -1.0                 NaN       February Kentucky Flooding             2          core
  CLM-6107264        -1.0                 NaN                    Hurricane Ida             2          core
  CLM-5654480        -5.0                 NaN  February West Virginia Flooding             2          core
  CLM-7853885        -3.0                 NaN                   Hurricane Zeta             0          core
  CLM-7579975        -9.0                 0.0               Hurricane Florence             4          core
  CLM-5693483        -2.0                 NaN                              NaN             2          core
  CLM-6785152        -6.0                 NaN                    Hurricane Ida             2          core
  CLM-6002424        -4.0                 NaN                    Hurricane Ian             1          core
  CLM-6350855        -7.0                 0.0                              NaN             4    legacy_bdx
  CLM-6205918        -1.0                 0.0               Hurricane Florence             4          core
  CLM-7138895        -7.0                 NaN                    Hurricane Ida             4          core
  CLM-7566597        -2.0                 NaN                              NaN             2          core
  CLM-7438811        -7.0                 NaN                              NaN             4          core
  CLM-5630816       -89.0                 0.0      Central U.S. April Flooding             4          core
  CLM-7222084        -3.0                 NaN                 Hurricane Isaias             4          core
  CLM-6351367        -5.0                 NaN              December Nor'easter             2          core
  CLM-6013753        -5.0                 NaN                              NaN             4          core
  CLM-5686745        -5.0                 NaN                    Hurricane Ida             4    legacy_bdx
  CLM-6349363        -6.0                 NaN                              NaN             2          core
  CLM-6726104        -8.0                 NaN Late-September New York Flooding             4          core
  CLM-8083812        -1.0                 NaN                              NaN             1          core
  CLM-7625221        -3.0                 NaN                    Hurricane Eta             4          core
  CLM-5564573        -8.0                 NaN                  Hurricane Sally             2          core
  CLM-7518508        -6.0                 NaN                 Hurricane Helene             2          core
  CLM-6765236        -2.0                 NaN                    Hurricane Ian             1          core
  CLM-6672082        -4.0                 0.0                              NaN             2          core
  CLM-5988759       -93.0                 NaN                              NaN             0          core
  CLM-7438862        -5.0                 NaN                              NaN             2          core
  CLM-7763959        -4.0                 NaN            June Midwest Flooding             2          core
  CLM-5718760        -7.0                 NaN                    Hurricane Ida             1          core
  CLM-5703432        -7.0                 NaN                              NaN             4          core
  CLM-7388713        -8.0                 NaN                  Hurricane Sally             1          core
  CLM-6787586        -7.0                 NaN                 Hurricane Helene             1          core
  CLM-6373524        -8.0                 NaN                              NaN             4          core
  CLM-5917318        -3.0                 NaN                              NaN             4          core
  CLM-7107691        -6.0                 NaN                 Hurricane Isaias             2          core
  CLM-5889577        -8.0                 NaN                    Hurricane Ida             4          core
  CLM-6127343       -57.0                 0.0       February Kentucky Flooding             2          core
  CLM-6829373        -7.0                 NaN                              NaN             2          core
  CLM-7927590        -9.0                 0.0               Hurricane Florence             1          core
  CLM-6568925        -4.0                 NaN                              NaN             4          core
  CLM-6334049        -7.0                 NaN                    Hurricane Ida             4          core
  CLM-5539407        -8.0                 NaN                              NaN             4          core
  CLM-5503684        -9.0                 0.0               Hurricane Florence             1          core
  CLM-7914105        -7.0                 NaN                    Hurricane Ida             4          core
  CLM-6810790        -6.0                 NaN                    Hurricane Ida             4          core
  CLM-8055414        -1.0                 NaN                    Hurricane Ian             2          core
  CLM-6396582        -8.0                 NaN                              NaN             4          core
  CLM-5762632        -9.0                 NaN                 Hurricane Helene             4          core
  CLM-5936139        -2.0                 NaN                              NaN             2          core
CLM-6888019-R        -7.0                 NaN                 Hurricane Helene             1          core
  CLM-6378525        -6.0                 NaN                  Hurricane Sally             1          core
  CLM-7461401        -1.0                 NaN                2026-06-Arthur-TS             4          core
  CLM-7100999        -7.0                 NaN                    Hurricane Ida             4          core
  CLM-6577220        -5.0                 NaN                    Hurricane Ida             4          core
  CLM-6363896        -9.0                 NaN                    Hurricane Ian             1          core
  CLM-6767884        -2.0                 NaN                              NaN             4          core
  CLM-7489924        -5.0                 NaN                    Hurricane Ida             2          core
  CLM-8078474        -6.0                 NaN                              NaN             4          core
  CLM-6008665        -5.0                 NaN                              NaN             4          core
  CLM-7471142        -5.0                 0.0                              NaN             4          core
  CLM-7589137        -8.0                 NaN                    Hurricane Ida             4          core
  CLM-7264623       -67.0                 NaN                              NaN             4          core
  CLM-5803715        -9.0                 NaN          Tropical Storm Nicholas             1          core
  CLM-6888019        -7.0                 NaN                 Hurricane Helene             1          core
  CLM-7518654        -1.0                 NaN            Tropical Storm Imelda             4          core
  CLM-5557469        -2.0                 NaN                              NaN             4          core
  CLM-7616582        -7.0                 0.0                              NaN             4          core
  CLM-7685251        -1.0                 0.0                              NaN             2          core
  CLM-7667828        -5.0                 NaN                    Hurricane Ian             1          core
  CLM-7073727       -20.0                 0.0                              NaN             4          core
  CLM-5880770        -3.0                 NaN                  Hurricane Debby             2          core
  CLM-8144536        -1.0                 NaN                 Hurricane Helene             1          core
CLM-7685251-R        -1.0                 0.0                              NaN             2          core
  CLM-6879727        -2.0                 NaN     California Atmospheric River             4          core
  CLM-6552836        -6.0                 NaN                              NaN             4          core
  CLM-7376940        -7.0                 2.0            June Midwest Flooding             2          core
  CLM-7047002        -1.0                 0.0                              NaN             2    legacy_bdx
  CLM-5999085        -2.0                 NaN                 Hurricane Helene             2          core
  CLM-6833813        -1.0                 NaN                 Hurricane Milton             1          core

In [40]:
df_clean[df_clean["waterDepth"] < 0]["source_system"].value_counts()

source_system
core          104
legacy_bdx      6
Name: count, dtype: int64

In [41]:
for col in [
    "amountPaidOnBuildingClaim",
    "amountPaidOnContentsClaim",
    "netBuildingPaymentAmount"
]:
    print(f"\n--- {col} ---")
    print(df_clean.loc[df_clean[col] < 0, col].value_counts())

--- amountPaidOnBuildingClaim ---
amountPaidOnBuildingClaim
-5.0    1
Name: count, dtype: int64

--- amountPaidOnContentsClaim ---
amountPaidOnContentsClaim
-1.0    1
Name: count, dtype: int64

--- netBuildingPaymentAmount ---
netBuildingPaymentAmount
-5.0    1
Name: count, dtype: int64

In [42]:
df_clean["nonPaymentReasonBuilding"].value_counts().sort_index()

nonPaymentReasonBuilding
1.0      70
6.0     110
7.0       2
8.0      10
15.0      1
16.0      2
20.0     38
97.0     62
98.0     20
99.0     74
Name: count, dtype: int64

# Clean 3
Fixing out of range latitude values

In [100]:
df_clean.loc[
    (df_clean["latitude"] < -90) |
    (df_clean["latitude"] > 90),
    "latitude"
] = float("nan")

In [44]:
negative_water = df_clean[df_clean["waterDepth"] < 0]

print(
    negative_water[
        [
            "claim_ref",
            "waterDepth",
            "floodWaterDuration",
            "floodEvent",
            "causeOfDamage",
            "source_system"
        ]
    ].to_string(index=False)
)

print("\nSource distribution:")
print(negative_water["source_system"].value_counts())

    claim_ref  waterDepth  floodWaterDuration                       floodEvent causeOfDamage source_system
  CLM-7898726        -7.0                 NaN Late-September New York Flooding             4    legacy_bdx
  CLM-6776458        -8.0                 NaN                              NaN             4          core
  CLM-8074075        -7.0                 NaN                              NaN             4          core
  CLM-7218663        -3.0                 NaN                              NaN             4          core
  CLM-6494245        -2.0                 NaN                    Hurricane Ida             2          core
  CLM-5800002        -5.0                 NaN                 Hurricane Milton             1          core
  CLM-7240110        -7.0                 NaN                    Hurricane Ida             4          core
  CLM-8118865        -3.0                 NaN                    Hurricane Ida             4          core
  CLM-5492313        -7.0                 NaN                              NaN             4          core
  CLM-5739653        -9.0                 NaN                              NaN             2          core
  CLM-5629942        -7.0                 NaN                              NaN             0          core
  CLM-5505937        -5.0                 NaN                              NaN             2          core
  CLM-7601909        -7.0                 0.0                              NaN             4          core
  CLM-7166295       -99.0                 NaN                              NaN             2          core
  CLM-7899950       -12.0                 NaN                 Hurricane Helene             1          core
  CLM-5889989        -4.0                 NaN                    Hurricane Ida             4          core
  CLM-5460824        -7.0                 NaN        Vermont/New York Flooding             4          core
  CLM-6134163        -2.0                 NaN                 Hurricane Helene             1    legacy_bdx
  CLM-6123171       -10.0                 NaN                              NaN             2          core
  CLM-6550216       -42.0                 NaN                 Hurricane Helene             1          core
  CLM-7159386        -1.0                 NaN                              NaN             1    legacy_bdx
  CLM-6566778        -1.0                 NaN                              NaN             2          core
  CLM-7937758        -8.0                 NaN                    Hurricane Ida             2          core
  CLM-5456412        -9.0                 0.0                              NaN             4          core
  CLM-7475750        -6.0                 0.0                              NaN             4          core
  CLM-5532848        -1.0                 0.0               Hurricane Florence             2          core
  CLM-8124449        -1.0                 NaN                 Hurricane Helene             4          core
  CLM-7930958        -3.0                 NaN                    Hurricane Ian             1          core
  CLM-8057247        -5.0                 0.0                              NaN             4          core
  CLM-6771568        -7.0                 NaN Late-September New York Flooding             4          core
  CLM-6708549        -1.0                 NaN       February Kentucky Flooding             2          core
  CLM-6107264        -1.0                 NaN                    Hurricane Ida             2          core
  CLM-5654480        -5.0                 NaN  February West Virginia Flooding             2          core
  CLM-7853885        -3.0                 NaN                   Hurricane Zeta             0          core
  CLM-7579975        -9.0                 0.0               Hurricane Florence             4          core
  CLM-5693483        -2.0                 NaN                              NaN             2          core
  CLM-6785152        -6.0                 NaN                    Hurricane Ida             2          core
  CLM-6002424        -4.0                 NaN                    Hurricane Ian             1          core
  CLM-6350855        -7.0                 0.0                              NaN             4    legacy_bdx
  CLM-6205918        -1.0                 0.0               Hurricane Florence             4          core
  CLM-7138895        -7.0                 NaN                    Hurricane Ida             4          core
  CLM-7566597        -2.0                 NaN                              NaN             2          core
  CLM-7438811        -7.0                 NaN                              NaN             4          core
  CLM-5630816       -89.0                 0.0      Central U.S. April Flooding             4          core
  CLM-7222084        -3.0                 NaN                 Hurricane Isaias             4          core
  CLM-6351367        -5.0                 NaN              December Nor'easter             2          core
  CLM-6013753        -5.0                 NaN                              NaN             4          core
  CLM-5686745        -5.0                 NaN                    Hurricane Ida             4    legacy_bdx
  CLM-6349363        -6.0                 NaN                              NaN             2          core
  CLM-6726104        -8.0                 NaN Late-September New York Flooding             4          core
  CLM-8083812        -1.0                 NaN                              NaN             1          core
  CLM-7625221        -3.0                 NaN                    Hurricane Eta             4          core
  CLM-5564573        -8.0                 NaN                  Hurricane Sally             2          core
  CLM-7518508        -6.0                 NaN                 Hurricane Helene             2          core
  CLM-6765236        -2.0                 NaN                    Hurricane Ian             1          core
  CLM-6672082        -4.0                 0.0                              NaN             2          core
  CLM-5988759       -93.0                 NaN                              NaN             0          core
  CLM-7438862        -5.0                 NaN                              NaN             2          core
  CLM-7763959        -4.0                 NaN            June Midwest Flooding             2          core
  CLM-5718760        -7.0                 NaN                    Hurricane Ida             1          core
  CLM-5703432        -7.0                 NaN                              NaN             4          core
  CLM-7388713        -8.0                 NaN                  Hurricane Sally             1          core
  CLM-6787586        -7.0                 NaN                 Hurricane Helene             1          core
  CLM-6373524        -8.0                 NaN                              NaN             4          core
  CLM-5917318        -3.0                 NaN                              NaN             4          core
  CLM-7107691        -6.0                 NaN                 Hurricane Isaias             2          core
  CLM-5889577        -8.0                 NaN                    Hurricane Ida             4          core
  CLM-6127343       -57.0                 0.0       February Kentucky Flooding             2          core
  CLM-6829373        -7.0                 NaN                              NaN             2          core
  CLM-7927590        -9.0                 0.0               Hurricane Florence             1          core
  CLM-6568925        -4.0                 NaN                              NaN             4          core
  CLM-6334049        -7.0                 NaN                    Hurricane Ida             4          core
  CLM-5539407        -8.0                 NaN                              NaN             4          core
  CLM-5503684        -9.0                 0.0               Hurricane Florence             1          core
  CLM-7914105        -7.0                 NaN                    Hurricane Ida             4          core
  CLM-6810790        -6.0                 NaN                    Hurricane Ida             4          core
  CLM-8055414        -1.0                 NaN                    Hurricane Ian             2          core
  CLM-6396582        -8.0                 NaN                              NaN             4          core
  CLM-5762632        -9.0                 NaN                 Hurricane Helene             4          core
  CLM-5936139        -2.0                 NaN                              NaN             2          core
CLM-6888019-R        -7.0                 NaN                 Hurricane Helene             1          core
  CLM-6378525        -6.0                 NaN                  Hurricane Sally             1          core
  CLM-7461401        -1.0                 NaN                2026-06-Arthur-TS             4          core
  CLM-7100999        -7.0                 NaN                    Hurricane Ida             4          core
  CLM-6577220        -5.0                 NaN                    Hurricane Ida             4          core
  CLM-6363896        -9.0                 NaN                    Hurricane Ian             1          core
  CLM-6767884        -2.0                 NaN                              NaN             4          core
  CLM-7489924        -5.0                 NaN                    Hurricane Ida             2          core
  CLM-8078474        -6.0                 NaN                              NaN             4          core
  CLM-6008665        -5.0                 NaN                              NaN             4          core
  CLM-7471142        -5.0                 0.0                              NaN             4          core
  CLM-7589137        -8.0                 NaN                    Hurricane Ida             4          core
  CLM-7264623       -67.0                 NaN                              NaN             4          core
  CLM-5803715        -9.0                 NaN          Tropical Storm Nicholas             1          core
  CLM-6888019        -7.0                 NaN                 Hurricane Helene             1          core
  CLM-7518654        -1.0                 NaN            Tropical Storm Imelda             4          core
  CLM-5557469        -2.0                 NaN                              NaN             4          core
  CLM-7616582        -7.0                 0.0                              NaN             4          core
  CLM-7685251        -1.0                 0.0                              NaN             2          core
  CLM-7667828        -5.0                 NaN                    Hurricane Ian             1          core
  CLM-7073727       -20.0                 0.0                              NaN             4          core
  CLM-5880770        -3.0                 NaN                  Hurricane Debby             2          core
  CLM-8144536        -1.0                 NaN                 Hurricane Helene             1          core
CLM-7685251-R        -1.0                 0.0                              NaN             2          core
  CLM-6879727        -2.0                 NaN     California Atmospheric River             4          core
  CLM-6552836        -6.0                 NaN                              NaN             4          core
  CLM-7376940        -7.0                 2.0            June Midwest Flooding             2          core
  CLM-7047002        -1.0                 0.0                              NaN             2    legacy_bdx
  CLM-5999085        -2.0                 NaN                 Hurricane Helene             2          core
  CLM-6833813        -1.0                 NaN                 Hurricane Milton             1          core

Source distribution:
source_system
core          104
legacy_bdx      6
Name: count, dtype: int64

In [45]:
payment_cols = [
    "amountPaidOnBuildingClaim",
    "amountPaidOnContentsClaim",
    "netBuildingPaymentAmount",
    "buildingDamageAmount",
    "contentsDamageAmount",
    "totalBuildingInsuranceCoverage",
    "totalContentsInsuranceCoverage"
]

df_clean[payment_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
amountPaidOnBuildingClaim,1848.0,78058.030813,821422.920655,-5.0,3706.42500,19630.58,74619.7525,34912215.45
amountPaidOnContentsClaim,1846.0,7862.331450,27670.506900,-1.0,0.00000,0.00,2560.3175,500000.00
netBuildingPaymentAmount,2040.0,50727.792065,121328.409769,-5.0,129.08125,14011.53,64447.3450,3447017.17
buildingDamageAmount,1820.0,58027.127110,127779.985377,0.0,4895.50000,19553.00,74653.2500,3085581.00
contentsDamageAmount,1136.0,16286.448781,62229.299250,0.0,0.00000,1548.50,15043.7500,1490364.00
totalBuildingInsuranceCoverage,2040.0,306770.013824,986798.148457,14.0,148875.00000,250000.00,250000.0000,20165000.00
totalContentsInsuranceCoverage,2040.0,47986.998039,61190.785520,0.0,0.00000,30000.00,100000.0000,500000.00

In [46]:
check = df_clean[
    df_clean["netBuildingPaymentAmount"] >
    df_clean["amountPaidOnBuildingClaim"]
]

print("Net > Building payment:", len(check))

print(check[
    [
        "claim_ref",
        "amountPaidOnBuildingClaim",
        "amountPaidOnContentsClaim",
        "netBuildingPaymentAmount",
        "buildingDamageAmount",
        "source_system"
    ]
].head(30))

Net > Building payment: 0
Empty DataFrame
Columns: [claim_ref, amountPaidOnBuildingClaim, amountPaidOnContentsClaim, netBuildingPaymentAmount, buildingDamageAmount, source_system]
Index: []

In [47]:
print(
    "Net == building payment:",
    (
        df_clean["netBuildingPaymentAmount"] ==
        df_clean["amountPaidOnBuildingClaim"]
    ).sum()
)

print(
    "Net > 0 while building payment = 0:",
    (
        (df_clean["netBuildingPaymentAmount"] > 0) &
        (df_clean["amountPaidOnBuildingClaim"] == 0)
    ).sum()
)

Net == building payment: 1833
Net > 0 while building payment = 0: 0

In [48]:
damage_property = df_clean[
    df_clean["buildingDamageAmount"] >
    df_clean["buildingPropertyValue"]
].copy()

damage_property["damage_to_property_ratio"] = (
    damage_property["buildingDamageAmount"] /
    damage_property["buildingPropertyValue"].replace(0, float("nan"))
)

print(
    damage_property[
        [
            "claim_ref",
            "buildingDamageAmount",
            "buildingPropertyValue",
            "buildingReplacementCost",
            "totalBuildingInsuranceCoverage",
            "damage_to_property_ratio",
            "source_system"
        ]
    ].sort_values(
        "damage_to_property_ratio",
        ascending=False
    ).head(20)
)

        claim_ref  buildingDamageAmount  buildingPropertyValue  \
943   CLM-7185471           1088937.000             213573.000
1221  CLM-6929169                78.213                 67.642
447   CLM-6788159            163666.000             148000.000
10    CLM-6726350            199577.000             180686.000
1147  CLM-8150954             23772.000              21772.000
1591  CLM-5459928            354174.000             348244.000
12    CLM-7820778            191858.000                  0.000
38    CLM-6601785             37970.000                  0.000
76    CLM-6732637            107206.000                  0.000
80    CLM-5826796             12165.000                  0.000
118   CLM-8009009              6436.000                  0.000
198   CLM-6967195            113858.000                  0.000
207   CLM-6018275                 1.000                  0.000
257   CLM-6488458             12000.000                  0.000
280   CLM-6906720             48119.000                  0.000
303   CLM-7330184                 1.000                  0.000
311   CLM-5868777                 1.000                  0.000
356   CLM-6519081              5000.000                  0.000
373   CLM-7279505             71250.000                  0.000
384   CLM-6550216             92307.000                  0.000

      buildingReplacementCost  totalBuildingInsuranceCoverage  \
943                255329.000                        250000.0
1221                  220.183                           141.0
447                223050.000                        165000.0
10                 358376.000                        250000.0
1147                38546.000                         66000.0
1591               404935.000                        500000.0
12                      0.000                        250000.0
38                      0.000                        223000.0
76                      0.000                        250000.0
80                      0.000                        250000.0
118                     0.000                        200000.0
198                     0.000                        149000.0
207                     0.000                        250000.0
257                     0.000                        250000.0
280                     0.000                         50000.0
303                     0.000                        250000.0
311                     0.000                        100000.0
356                     0.000                        200000.0
373                     0.000                        220000.0
384                     0.000                        218000.0

      damage_to_property_ratio source_system
943                   5.098664          core
1221                  1.156279    legacy_bdx
447                   1.105851          core
10                    1.104552          core
1147                  1.091861          core
1591                  1.017028          core
12                         NaN          core
38                         NaN          core
76                         NaN          core
80                         NaN          core
118                        NaN          core
198                        NaN          core
207                        NaN          core
257                        NaN          core
280                        NaN          core
303                        NaN          core
311                        NaN          core
356                        NaN          core
373                        NaN          core
384                        NaN          core

In [49]:
damage_replacement = df_clean[
    df_clean["buildingDamageAmount"] >
    df_clean["buildingReplacementCost"]
].copy()

damage_replacement["damage_to_replacement_ratio"] = (
    damage_replacement["buildingDamageAmount"] /
    damage_replacement["buildingReplacementCost"].replace(0, float("nan"))
)

print(
    damage_replacement[
        [
            "claim_ref",
            "buildingDamageAmount",
            "buildingReplacementCost",
            "buildingPropertyValue",
            "totalBuildingInsuranceCoverage",
            "damage_to_replacement_ratio",
            "source_system"
        ]
    ].sort_values(
        "damage_to_replacement_ratio",
        ascending=False
    ).head(20)
)

       claim_ref  buildingDamageAmount  buildingReplacementCost  \
943  CLM-7185471             1088937.0                 255329.0
12   CLM-7820778              191858.0                      0.0
38   CLM-6601785               37970.0                      0.0
76   CLM-6732637              107206.0                      0.0
80   CLM-5826796               12165.0                      0.0
118  CLM-8009009                6436.0                      0.0
134  CLM-6830799                 103.0                      0.0
198  CLM-6967195              113858.0                      0.0
207  CLM-6018275                   1.0                      0.0
257  CLM-6488458               12000.0                      0.0
280  CLM-6906720               48119.0                      0.0
303  CLM-7330184                   1.0                      0.0
311  CLM-5868777                   1.0                      0.0
356  CLM-6519081                5000.0                      0.0
373  CLM-7279505               71250.0                      0.0
384  CLM-6550216               92307.0                      0.0
414  CLM-5543326                8261.0                      0.0
535  CLM-6925981               24107.0                      0.0
543  CLM-7905386               48219.0                      0.0
596  CLM-7716214               26779.0                      0.0

     buildingPropertyValue  totalBuildingInsuranceCoverage  \
943               213573.0                        250000.0
12                     0.0                        250000.0
38                     0.0                        223000.0
76                     0.0                        250000.0
80                     0.0                        250000.0
118                    0.0                        200000.0
134               149284.0                        250000.0
198                    0.0                        149000.0
207                    0.0                        250000.0
257                    0.0                        250000.0
280                    0.0                         50000.0
303                    0.0                        250000.0
311                    0.0                        100000.0
356                    0.0                        200000.0
373                    0.0                        220000.0
384                    0.0                        218000.0
414                    0.0                         30000.0
535                    0.0                        224000.0
543                    0.0                        250000.0
596                    0.0                        156100.0

     damage_to_replacement_ratio source_system
943                     4.264839          core
12                           NaN          core
38                           NaN          core
76                           NaN          core
80                           NaN          core
118                          NaN          core
134                          NaN          core
198                          NaN          core
207                          NaN          core
257                          NaN          core
280                          NaN          core
303                          NaN          core
311                          NaN          core
356                          NaN          core
373                          NaN          core
384                          NaN          core
414                          NaN          core
535                          NaN          core
543                          NaN          core
596                          NaN          core

In [50]:
zero_values = df_clean[
    (df_clean["buildingPropertyValue"] == 0) |
    (df_clean["buildingReplacementCost"] == 0)
].copy()

print("Rows:", len(zero_values))

print("\nSource system:")
print(zero_values["source_system"].value_counts())

print("\nBoth zero:")
print(
    (
        (zero_values["buildingPropertyValue"] == 0) &
        (zero_values["buildingReplacementCost"] == 0)
    ).sum()
)

print("\nOnly property value zero:")
print(
    (
        (zero_values["buildingPropertyValue"] == 0) &
        (zero_values["buildingReplacementCost"] != 0)
    ).sum()
)

print("\nOnly replacement cost zero:")
print(
    (
        (zero_values["buildingPropertyValue"] != 0) &
        (zero_values["buildingReplacementCost"] == 0)
    ).sum()
)

Rows: 167

Source system:
source_system
core          158
legacy_bdx      9
Name: count, dtype: int64

Both zero:
159

Only property value zero:
4

Only replacement cost zero:
4

In [51]:
df_clean[
    df_clean["claim_ref"] == "CLM-7185471"
].T

                                                          943
claim_ref                                         CLM-7185471
source_system                                            core
dateOfLoss                          2022-07-26 00:00:00+00:00
yearOfLoss                                               2022
state                                                      MO
reportedZipCode                                         63043
countyCode                                            29189.0
latitude                                                 38.7
longitude                                               -90.4
floodEvent                                 Late July Flooding
causeOfDamage                                               2
ratedFloodZone                                             AE
occupancyType                                              11
numberOfFloorsInTheInsuredBuilding                        1.0
originalConstructionDate            1968-01-01 00:00:00+00:00
elevatedBuildingIndicator                                   0
primaryResidenceIndicator                                   1
totalBuildingInsuranceCoverage                       250000.0
totalContentsInsuranceCoverage                        70000.0
buildingPropertyValue                                213573.0
buildingReplacementCost                              255329.0
buildingDamageAmount                                1088937.0
contentsDamageAmount                                      NaN
waterDepth                                                1.0
floodWaterDuration                                        NaN
amountPaidOnBuildingClaim                            205516.2
amountPaidOnContentsClaim                                 0.0
netBuildingPaymentAmount                             205516.2
nonPaymentReasonBuilding                                  NaN
openDate                            2022-07-26 00:00:00+00:00
mostRecentPaymentDate               2025-06-11 00:00:00+00:00

In [52]:
print("Building damage < $100:")
print(
    df_clean[
        df_clean["buildingDamageAmount"].notna() &
        (df_clean["buildingDamageAmount"] < 100)
    ][[
        "claim_ref",
        "buildingDamageAmount",
        "buildingPropertyValue",
        "buildingReplacementCost",
        "amountPaidOnBuildingClaim",
        "source_system"
    ]].to_string(index=False)
)

Building damage < $100:
    claim_ref  buildingDamageAmount  buildingPropertyValue  buildingReplacementCost  amountPaidOnBuildingClaim source_system
  CLM-5642877                 0.000                  0.000                    0.000                      0.000          core
  CLM-5976757                87.000              86092.000               131458.000                      0.000          core
  CLM-5576313                 0.000                  0.000                    0.000                        NaN          core
  CLM-7455343                 0.000             132438.000               228342.000                      0.000          core
  CLM-6223381                 0.000             293000.000               329700.000                      0.000          core
  CLM-5637999                 0.000             150000.000               150000.000                        NaN          core
  CLM-7806166                 0.000             311295.000               371882.000                      0.000          core
CLM-6839569-R                 0.000                  0.000                    0.000                        NaN          core
  CLM-7898726                 3.179                259.649                  343.112                      2.179    legacy_bdx
  CLM-7736420                 0.000                  0.000                    0.000                      0.000          core
  CLM-5746454                76.453                420.902                  466.860                     74.453    legacy_bdx
  CLM-6157209                19.150                265.987                  321.987                     14.150    legacy_bdx
  CLM-7948788                 0.000                  0.000                    0.000                      0.000          core
  CLM-6454676                 0.000             158948.000               305669.000                      0.000          core
  CLM-6470168                17.635                161.529                  299.727                     16.385    legacy_bdx
  CLM-7282269                 0.000                  0.000                    0.000                        NaN          core
  CLM-6736067                 0.000                  0.000                    0.000                      0.000          core
CLM-7433935-R                 0.000                  0.000                    0.000                      0.000          core
  CLM-6398916                 7.832                567.325                  679.768                      2.832    legacy_bdx
  CLM-5533201                 0.000                  0.000                    0.000                      0.000          core
  CLM-7011673                 8.493                 83.844                  203.775                      3.493    legacy_bdx
  CLM-5725175                 0.000                  0.000                    0.000                        NaN    legacy_bdx
  CLM-5848380                 0.000                  0.000                    0.000                      0.000    legacy_bdx
  CLM-6280924                 0.000             133333.000               181543.000                      0.000          core
  CLM-8169782                 7.235                203.092                  255.781                      5.235    legacy_bdx
  CLM-6916300                73.476                249.000                  250.000                     68.476    legacy_bdx
  CLM-7035384                 0.000             407256.000               497430.000                      0.000          core
  CLM-6331570                 0.000                  0.000                    0.000                      0.000          core
  CLM-6942823                 0.000                  0.000                    0.000                      0.000          core
  CLM-6900484                 0.000              26000.000                27448.000                   4392.540          core
CLM-7127665-R                10.031                166.317                  212.107                      9.465    legacy_bdx
  CLM-7217432                 0.000                  0.000                    0.000                      0.000          core
  CLM-7325864                 0.000                  0.000                    0.000                   2425.310          core
  CLM-6018275                 1.000                  0.000                    0.000                      0.000          core
  CLM-6799102                 3.299                235.303                    3.564                      2.049    legacy_bdx
  CLM-5622848                 0.000             214124.000               227792.000                      0.000          core
  CLM-7433935                 0.000                  0.000                    0.000                      0.000          core
  CLM-6409025                 8.035                120.714                  165.556                      6.036    legacy_bdx
  CLM-7166295                 0.000                  0.000               128948.000                   2040.760          core
  CLM-5919560                 0.000             408626.000               468856.000                      0.000          core
  CLM-5493394                 0.000              90000.000               100000.000                      0.000          core
  CLM-7120869                 0.000                  0.000                    0.000                      0.000          core
  CLM-7689439                 0.000             265078.000               265078.000                        NaN          core
  CLM-7159799                 0.000             254769.000               326423.000                      0.000          core
  CLM-7330184                 1.000                  0.000                    0.000                  14084.080          core
  CLM-5868777                 1.000                  0.000                    0.000                  33192.010          core
  CLM-6134163                14.736                177.858                  260.973                      6.019    legacy_bdx
  CLM-5897469                57.566                181.027                  201.141                     78.889    legacy_bdx
  CLM-6875008                 0.000             173656.000               263626.000                        NaN          core
  CLM-7960288                 0.000             144232.000               169346.000                      0.000          core
  CLM-7338211                 0.000                  0.000                    0.000                      0.000          core
  CLM-8106199                87.210                693.814                  786.415                     77.210    legacy_bdx
  CLM-7805331                 0.000                  0.000                    0.000                        NaN          core
  CLM-7522505                 0.000                  0.000                    0.000                        NaN          core
  CLM-7159386                 8.268                153.554                  201.304                      8.612    legacy_bdx
  CLM-8006965                 0.000             168475.000               187195.000                      0.000          core
  CLM-7701299                12.976                145.726                  181.553                     13.282    legacy_bdx
  CLM-8099259                 0.000                  0.000                    0.000                        NaN          core
  CLM-6877029                 0.000                  0.000                  229.189                        NaN    legacy_bdx
  CLM-7302971                 0.000                  0.000                    0.000                      0.000          core
  CLM-6304365                41.481                140.243                  210.124                     34.796    legacy_bdx
  CLM-7173174                 0.000                  0.000                    0.000                      0.000          core
  CLM-7648582                 3.805                249.409                  486.197                      0.000    legacy_bdx
  CLM-6842414                 0.000                  0.000                    0.000                      0.000          core
  CLM-7153069                 0.000                  0.000                    0.000                      0.000          core
  CLM-6410405                39.740                106.482                  143.262                     38.240    legacy_bdx
  CLM-5726698                 0.000             335453.000               413912.000                      0.000          core
  CLM-6729784                87.757                100.694                  106.448                     90.000    legacy_bdx
  CLM-6658432                 0.000             104073.000               254219.000                   1293.620          core
  CLM-6053106                 0.000                  0.000                    0.000                        NaN          core
  CLM-5611558                 0.000                100.000                    0.000                      0.000          core
  CLM-6134144                 0.000                  0.000                    0.000                      0.000    legacy_bdx
  CLM-7532726                 0.000                  0.000                    0.000                        NaN          core
  CLM-5925198                 0.000                  0.000                    0.000                      0.000          core
  CLM-6611416                33.281                246.069                  306.994                     32.031    legacy_bdx
  CLM-6498588                 0.000                  0.000                    0.000                      0.000          core
  CLM-5955654                44.993                 92.707                  122.718                     52.237    legacy_bdx
  CLM-6798980                64.482                 68.424                   85.530                     53.100    legacy_bdx
  CLM-7317886                 0.000                  0.000                    0.000                        NaN          core
  CLM-5888360                 0.000             278346.000               410279.000                      0.000          core
  CLM-7535267                 0.000                  0.000                    0.000                        NaN          core
  CLM-7408518                 0.000                  0.000                    0.000                      0.000          core
  CLM-7498913                 0.000                  0.000                    0.000                        NaN          core
  CLM-6834021                 0.000                  0.000                    0.000                      0.000          core
  CLM-5651249                29.319                571.475                  697.835                     27.319    legacy_bdx
  CLM-5619471                70.332                185.713                  234.061                     73.215    legacy_bdx
  CLM-5662806                 8.883                231.889                  308.622                     18.417    legacy_bdx
  CLM-5632217                 1.000                  0.000                    0.000                 140521.190          core
  CLM-6900261                 1.000                  0.000                    0.000                 121342.480          core
  CLM-7325567                 0.000             250000.000               250000.000                        NaN          core
  CLM-6262285                 0.855                 96.771                  153.429                      0.822    legacy_bdx
  CLM-8163365                 0.000             150000.000               150000.000                        NaN          core
  CLM-7032381                 1.000                  0.000                    0.000                  92289.460          core
  CLM-6885506                77.542                188.182                  246.786                     87.665    legacy_bdx
  CLM-5666358                 0.000             301542.000               343693.000                      0.000          core
  CLM-8054169                 0.000                  0.000                    0.000                      0.000          core
  CLM-7529391                13.259                 96.873                  160.369                     14.759    legacy_bdx
  CLM-6716426                 0.000             257101.000               381656.000                      0.000          core
  CLM-7023722                 0.000              62875.000                68357.000                      0.000          core
  CLM-5752148                 0.000                303.038                  397.472                     21.601    legacy_bdx
  CLM-7791153                20.788                183.390                  258.102                     15.788    legacy_bdx
  CLM-6179160                 1.000                  0.000                    0.000                   9586.200          core
  CLM-6372481                 0.000             205069.000               258064.000                      0.000          core
  CLM-7515271                 6.927                203.586                  233.529                      1.927    legacy_bdx
  CLM-6155617                27.213                 90.893                  144.275                     25.964    legacy_bdx
  CLM-7672876                 0.000                  0.000                    0.000                      0.000          core
  CLM-6454627                 0.000            2313292.000              2545946.000                      0.000          core
  CLM-7831395                 0.000             250000.000               250000.000                        NaN          core
  CLM-7507137                 0.000             338134.000               378754.000                   6320.530          core
  CLM-6043281                95.298                138.532                  173.165                     94.048    legacy_bdx
  CLM-6638809                 7.872                 11.420                   20.361                      6.372    legacy_bdx
  CLM-7801802                 0.000             187737.000               213072.000                      0.000          core
  CLM-6505015                 8.680                112.312                  562.942                      7.431    legacy_bdx
  CLM-7512775                 0.000                  0.000                    0.000                      0.000          core
  CLM-7787456                 0.000                  0.000                    0.000                        NaN          core
  CLM-7302663                 0.000                  0.000                    0.000                        NaN          core
  CLM-5477807                 0.000                  0.000                    0.000                      0.000          core
  CLM-8066334                 0.000              59700.000                59700.000                        NaN          core
  CLM-5686745                17.070                 85.536                  134.500                     15.821    legacy_bdx
  CLM-5469619                 0.000             209583.000               238162.000                      0.000          core
  CLM-8111208                 0.000                197.859                  236.869                      0.000    legacy_bdx
  CLM-7830371                 7.852                370.093                  410.453                      6.602    legacy_bdx
  CLM-8091327                 7.011                298.204                  333.891                      5.761    legacy_bdx
  CLM-6392488                 0.000                  0.000                    0.000                      0.000          core
  CLM-8104388                 0.000                  0.000                    0.000                      0.000          core
  CLM-8128223                 0.000                  0.000                    0.000                      0.000          core
  CLM-6525843                 0.000             191961.000               502135.000                        NaN          core
CLM-6576331-R                 0.000                  0.000                    0.000                      0.000          core
  CLM-7548551                 7.343                185.902                  368.627                      6.092    legacy_bdx
  CLM-7498965                15.304                160.384                  297.007                     14.054    legacy_bdx
  CLM-7812741                 0.000              91944.000               105310.000                      0.000          core
  CLM-6375439                 0.000             188676.000               227320.000                      0.000          core
  CLM-6108302                 0.000                  0.000                    0.000                      0.000          core
  CLM-7579642                25.646                143.154                  180.622                     24.396    legacy_bdx
  CLM-6539222                 0.000             118121.000               155422.000                      0.000          core
  CLM-7769047                 0.000              75000.000                75000.000                      0.000          core
  CLM-5947909                 0.000              94927.000               147690.000                      0.000          core
  CLM-7137299                12.130                 83.341                  127.165                     10.880    legacy_bdx
  CLM-7154736                 0.000             135645.000               168738.000                      0.000          core
  CLM-5616891                 0.000                134.077                  155.904                      0.000    legacy_bdx
  CLM-7001792                 0.000                  0.000                    0.000                        NaN          core
  CLM-6556909                48.387                174.726                  225.662                     38.387    legacy_bdx
  CLM-6665337                24.558                141.826                  184.189                     22.558    legacy_bdx
  CLM-6177307                 0.000                  0.000                    0.000                      0.000          core
  CLM-6043828                 0.000             147424.000               177619.000                      0.000          core
  CLM-7548305                 1.000                  0.000                    0.000                   2010.120          core
  CLM-7634999                 0.000                  0.000                    0.000                      0.000          core
  CLM-6810449                 0.000                  0.000                    0.000                      0.000          core
  CLM-7858008                 0.000                  0.000                    0.000                      0.000          core
  CLM-7991314                 0.000             489610.000               558797.000                      0.000          core
  CLM-6281112                78.929                695.733                  850.309                     77.679    legacy_bdx
  CLM-7448056                 0.000             756657.000              1201043.000                      0.000          core
  CLM-5900303                 0.000             237600.000               296094.000                      0.000          core
  CLM-7923440                31.571                201.667                  245.252                     29.571    legacy_bdx
  CLM-8173690                 0.000                  0.000                    0.000                      0.000          core
  CLM-5790968                 0.000                  0.000                    0.000                        NaN          core
  CLM-5873679                 0.000             200431.000               537726.000                      0.000          core
CLM-5598359-R                 0.000                  0.000                    0.000                      0.000    legacy_bdx

In [53]:
print("Property value < $100:")
print(
    df_clean[
        df_clean["buildingPropertyValue"].notna() &
        (df_clean["buildingPropertyValue"] < 100)
    ][[
        "claim_ref",
        "buildingPropertyValue",
        "buildingReplacementCost",
        "buildingDamageAmount",
        "source_system"
    ]].to_string(index=False)
)

Property value < $100:
    claim_ref  buildingPropertyValue  buildingReplacementCost  buildingDamageAmount source_system
  CLM-5642877                  0.000                    0.000                 0.000          core
  CLM-7820778                  0.000                    0.000            191858.000          core
  CLM-5576313                  0.000                    0.000                 0.000          core
CLM-6839569-R                  0.000                    0.000                 0.000          core
  CLM-6601785                  0.000                    0.000             37970.000          core
  CLM-7736420                  0.000                    0.000                 0.000          core
  CLM-6732637                  0.000                    0.000            107206.000          core
  CLM-5826796                  0.000                    0.000             12165.000          core
  CLM-7948788                  0.000                    0.000                 0.000          core
  CLM-7282269                  0.000                    0.000                 0.000          core
  CLM-8009009                  0.000                    0.000              6436.000          core
  CLM-6736067                  0.000                    0.000                 0.000          core
CLM-7433935-R                  0.000                    0.000                 0.000          core
  CLM-5533201                  0.000                    0.000                 0.000          core
  CLM-7011673                 83.844                  203.775                 8.493    legacy_bdx
  CLM-5725175                  0.000                    0.000                 0.000    legacy_bdx
  CLM-5848380                  0.000                    0.000                 0.000    legacy_bdx
  CLM-6331570                  0.000                    0.000                 0.000          core
  CLM-6942823                  0.000                    0.000                 0.000          core
  CLM-7217432                  0.000                    0.000                 0.000          core
  CLM-7325864                  0.000                    0.000                 0.000          core
  CLM-6967195                  0.000                    0.000            113858.000          core
  CLM-6018275                  0.000                    0.000                 1.000          core
  CLM-7433935                  0.000                    0.000                 0.000          core
  CLM-7166295                  0.000               128948.000                 0.000          core
  CLM-6488458                  0.000                    0.000             12000.000          core
  CLM-7120869                  0.000                    0.000                 0.000          core
  CLM-6906720                  0.000                    0.000             48119.000          core
  CLM-7330184                  0.000                    0.000                 1.000          core
  CLM-5868777                  0.000                    0.000                 1.000          core
  CLM-6519081                  0.000                    0.000              5000.000          core
  CLM-7338211                  0.000                    0.000                 0.000          core
  CLM-7805331                  0.000                    0.000                 0.000          core
  CLM-7522505                  0.000                    0.000                 0.000          core
  CLM-7279505                  0.000                    0.000             71250.000          core
  CLM-6550216                  0.000                    0.000             92307.000          core
  CLM-5543326                  0.000                    0.000              8261.000          core
  CLM-8099259                  0.000                    0.000                 0.000          core
  CLM-6877029                  0.000                  229.189                 0.000    legacy_bdx
  CLM-7302971                  0.000                    0.000                 0.000          core
  CLM-7173174                  0.000                    0.000                 0.000          core
  CLM-6842414                  0.000                    0.000                 0.000          core
  CLM-7153069                  0.000                    0.000                 0.000          core
  CLM-6053106                  0.000                    0.000                 0.000          core
  CLM-6134144                  0.000                    0.000                 0.000    legacy_bdx
  CLM-7532726                  0.000                    0.000                 0.000          core
  CLM-5925198                  0.000                    0.000                 0.000          core
  CLM-6925981                  0.000                    0.000             24107.000          core
  CLM-7905386                  0.000                    0.000             48219.000          core
  CLM-6498588                  0.000                    0.000                 0.000          core
  CLM-5955654                 92.707                  122.718                44.993    legacy_bdx
  CLM-6798980                 68.424                   85.530                64.482    legacy_bdx
  CLM-7716214                  0.000                    0.000             26779.000          core
  CLM-7317886                  0.000                    0.000                 0.000          core
  CLM-8041105                  0.000                    0.000            114000.000          core
  CLM-7535267                  0.000                    0.000                 0.000          core
  CLM-7408518                  0.000                    0.000                 0.000          core
  CLM-7498913                  0.000                    0.000                 0.000          core
  CLM-6834021                  0.000                    0.000                 0.000          core
  CLM-5632217                  0.000                    0.000                 1.000          core
  CLM-6900261                  0.000                    0.000                 1.000          core
  CLM-6262285                 96.771                  153.429                 0.855    legacy_bdx
  CLM-7032381                  0.000                    0.000                 1.000          core
  CLM-8054169                  0.000                    0.000                 0.000          core
  CLM-7529391                 96.873                  160.369                13.259    legacy_bdx
  CLM-6179160                  0.000                    0.000                 1.000          core
  CLM-5500843                  0.000                    0.000            135856.000          core
  CLM-6155617                 90.893                  144.275                27.213    legacy_bdx
  CLM-7672876                  0.000                    0.000                 0.000          core
  CLM-5646266                  0.000                    0.000            210317.000          core
  CLM-6638809                 11.420                   20.361                 7.872    legacy_bdx
  CLM-5669449                  0.000                    0.000            148042.000          core
  CLM-7512775                  0.000                    0.000                 0.000          core
  CLM-5507607                  0.000                    0.000             13000.000          core
  CLM-7787456                  0.000                    0.000                 0.000          core
  CLM-6145841                  0.000                    0.000             24799.000          core
  CLM-7302663                  0.000                    0.000                 0.000          core
  CLM-6166211                  0.000                    0.000             14842.000          core
  CLM-5477807                  0.000                    0.000                 0.000          core
  CLM-5686745                 85.536                  134.500                17.070    legacy_bdx
  CLM-6061699                  0.000                    0.000             57972.000          core
  CLM-6392488                  0.000                    0.000                 0.000          core
  CLM-8104388                  0.000                    0.000                 0.000          core
  CLM-8128223                  0.000                    0.000                 0.000          core
  CLM-7030610                  0.000                    0.000            358678.000          core
CLM-6576331-R                  0.000                    0.000                 0.000          core
  CLM-7804802                  0.000                    0.000             64101.000          core
  CLM-5536809                  0.000                    0.000             17749.000          core
  CLM-6108302                  0.000                    0.000                 0.000          core
  CLM-6309618                  0.000                    0.000             41771.000          core
  CLM-7137299                 83.341                  127.165                12.130    legacy_bdx
  CLM-5939697                  0.000                    0.000             12395.000          core
  CLM-7961163                  0.000                    0.000             97622.000          core
  CLM-7164084                  0.000                    0.000             21613.000          core
  CLM-6100572                  0.000                    0.000             77000.000          core
  CLM-7294870                  0.000                    0.000            164796.000          core
  CLM-7244473                  0.000                    0.000             12701.000          core
  CLM-7001792                  0.000                    0.000                 0.000          core
  CLM-7738044                  0.000                    0.000             36845.000          core
  CLM-6177307                  0.000                    0.000                 0.000          core
  CLM-7548305                  0.000                    0.000                 1.000          core
  CLM-5513532                  0.000                    0.000            192502.000          core
  CLM-7634999                  0.000                    0.000                 0.000          core
  CLM-6810449                  0.000                    0.000                 0.000          core
  CLM-7858008                  0.000                    0.000                 0.000          core
  CLM-8173690                  0.000                    0.000                 0.000          core
  CLM-5790968                  0.000                    0.000                 0.000          core
CLM-5598359-R                  0.000                    0.000                 0.000    legacy_bdx
  CLM-7902729                  0.000                    0.000                 0.000          core
  CLM-6929169                 67.642                  220.183                78.213    legacy_bdx
  CLM-7357370                  0.000                    0.000                 0.000          core
  CLM-7018284                  0.000                    0.000            308019.000          core
  CLM-7798283                  0.000                    0.000                 0.000          core
  CLM-7654689                  0.000                    0.000                 0.000          core
  CLM-7850883                  0.000                    0.000                 0.000          core
  CLM-7011831                  0.000                    0.000             21344.000          core
  CLM-7783197                  0.000                    0.000             17640.000          core
  CLM-7532780                  0.000                    0.000              8147.000          core
  CLM-6812106                  0.000                    0.000             16133.000          core
  CLM-6467922                  0.000                    0.000                 0.000          core
  CLM-7225648                  0.000                    0.000                 0.000          core
  CLM-7244619                  0.000                    0.000                 1.000          core
  CLM-6686655                  0.000                    0.000                 0.000          core
  CLM-7780480                  0.000                    0.000                 0.000          core
  CLM-7557995                  0.000                    0.000                 0.000          core
  CLM-6021248                  0.000                    0.000                 0.000          core
  CLM-6449644                  0.000                    0.000            507406.000          core
  CLM-6807961                  0.000                    0.000                 0.000          core
  CLM-5470901                  0.000                    0.000                 1.000          core
  CLM-5828697                  0.000                    0.000            227109.000          core
  CLM-7270798                  0.000                    0.000                 1.000          core
  CLM-6877186                  0.000                    0.000                 0.000          core
  CLM-5651070                  0.000                    0.000               150.763    legacy_bdx
  CLM-5508350                  0.000                    0.000                 0.000          core
  CLM-7301615                  0.000                    0.000                 0.000          core
  CLM-8102217                  0.000                    0.000            120000.000          core
  CLM-7936455                  0.000                    0.000              7577.000          core
  CLM-6812486                  0.000                    0.000                 0.000          core
  CLM-5731667                  0.000              1969208.000             13728.000          core
  CLM-6274943                  0.000                    0.000                 0.000          core
  CLM-6333060                  0.000                    0.000                 0.000          core
  CLM-5907432                  0.000                    0.000              5720.000          core
  CLM-7848284                  0.000                    0.000             38486.000          core
  CLM-6274101                  0.000                    0.000             97217.000          core
  CLM-5816219                  0.000                    0.000                 0.000    legacy_bdx
  CLM-8087807                  0.000                    0.000                 1.000          core
  CLM-5598359                  0.000                    0.000                 0.000    legacy_bdx
CLM-6145841-R                  0.000                    0.000             24799.000          core
  CLM-7282771                  0.000                    0.000                 1.000          core
CLM-7936455-R                  0.000                    0.000              7577.000          core
  CLM-6798651                  0.000                    0.000                 0.000    legacy_bdx
  CLM-6147944                  0.000                    0.000                 0.000          core
  CLM-6576331                  0.000                    0.000                 0.000          core
  CLM-7871324                  0.000                    0.000                 1.000          core
  CLM-6096948                  0.000                    0.000                 0.000          core
  CLM-7653381                  0.000                    0.000                 0.000          core
  CLM-8072420                  0.000                    0.000                 0.000          core
  CLM-6284078                  0.000                    0.000                 0.000          core
  CLM-6839569                  0.000                    0.000                 0.000          core
  CLM-7519660                  0.000                    0.000                 0.000          core
  CLM-5873314                  0.000                    0.000                 0.000          core
  CLM-7300874                  0.000                    0.000              4229.000          core
  CLM-6954206                  0.000                    0.000                 0.000          core
  CLM-5840371                  0.000                    0.000             81627.000          core
  CLM-5632534                  0.000               330013.000             37254.000          core
  CLM-6680557                 77.731                  116.344                17.277    legacy_bdx
  CLM-6755271                  0.000                    0.000                 0.000          core
  CLM-6504278                  0.000                    0.000                 0.000          core
  CLM-5797323                  0.000                    0.000                 0.000          core
  CLM-6384572                  0.000                    0.000                 0.000          core
  CLM-5472105                  0.000                    0.000             61620.000          core
  CLM-7169458                  0.000                    0.000              6154.000          core
  CLM-5767997                  0.000                    0.000                 0.000          core
  CLM-6629976                  0.000                    0.000                 1.000          core

In [54]:
money_cols = [
    "totalBuildingInsuranceCoverage",
    "totalContentsInsuranceCoverage",
    "buildingPropertyValue",
    "buildingReplacementCost",
    "buildingDamageAmount",
    "contentsDamageAmount",
    "amountPaidOnBuildingClaim",
    "amountPaidOnContentsClaim",
    "netBuildingPaymentAmount"
]

df_clean.groupby("source_system")[money_cols].median().T

source_system                        core  legacy_bdx
totalBuildingInsuranceCoverage  250000.00     250.000
totalContentsInsuranceCoverage   40000.00      46.000
buildingPropertyValue           191799.00     181.113
buildingReplacementCost         251887.00     234.752
buildingDamageAmount             23372.00      23.697
contentsDamageAmount              2318.00       6.314
amountPaidOnBuildingClaim        23405.74      21.933
amountPaidOnContentsClaim            0.00       0.000
netBuildingPaymentAmount         16658.82      16.385

## Clean 4
Monetary values in legacy_bdx are stored in thousands, while values in core are stored in dollars.

In [55]:
monetary_cols = [
    "totalBuildingInsuranceCoverage",
    "totalContentsInsuranceCoverage",
    "buildingPropertyValue",
    "buildingReplacementCost",
    "buildingDamageAmount",
    "contentsDamageAmount",
    "amountPaidOnBuildingClaim",
    "amountPaidOnContentsClaim",
    "netBuildingPaymentAmount"
]

legacy_mask = df_clean["source_system"] == "legacy_bdx"

df_clean.loc[legacy_mask, monetary_cols] = (
    df_clean.loc[legacy_mask, monetary_cols] * 1000
)

In [56]:
df_clean.groupby("source_system")[monetary_cols].median().T

source_system                        core  legacy_bdx
totalBuildingInsuranceCoverage  250000.00    250000.0
totalContentsInsuranceCoverage   40000.00     46000.0
buildingPropertyValue           191799.00    181113.0
buildingReplacementCost         251887.00    234752.0
buildingDamageAmount             23372.00     23697.0
contentsDamageAmount              2318.00      6314.0
amountPaidOnBuildingClaim        23405.74     21933.0
amountPaidOnContentsClaim            0.00         0.0
netBuildingPaymentAmount         16658.82     16385.0

In [57]:
print("Legacy rows:", legacy_mask.sum())

print(
    df_clean.groupby("source_system")[
        ["totalBuildingInsuranceCoverage", "buildingDamageAmount"]
    ].median()
)

Legacy rows: 123
               totalBuildingInsuranceCoverage  buildingDamageAmount
source_system
core                                 250000.0               23372.0
legacy_bdx                           250000.0               23697.0

In [58]:
checks = {
    "damage_gt_property": (
        df_clean["buildingDamageAmount"] >
        df_clean["buildingPropertyValue"]
    ),
    "damage_gt_replacement": (
        df_clean["buildingDamageAmount"] >
        df_clean["buildingReplacementCost"]
    ),
    "payment_gt_coverage": (
        df_clean["amountPaidOnBuildingClaim"] >
        df_clean["totalBuildingInsuranceCoverage"]
    ),
    "negative_building_payment": (
        df_clean["amountPaidOnBuildingClaim"] < 0
    )
}

for name, mask in checks.items():
    print(name, mask.sum())

damage_gt_property 77
damage_gt_replacement 73
payment_gt_coverage 21
negative_building_payment 1

In [59]:
damage_value_issues = df_clean[
    (df_clean["buildingDamageAmount"] > df_clean["buildingPropertyValue"]) |
    (df_clean["buildingDamageAmount"] > df_clean["buildingReplacementCost"])
][[
    "claim_ref",
    "source_system",
    "state",
    "dateOfLoss",
    "buildingPropertyValue",
    "buildingReplacementCost",
    "buildingDamageAmount",
    "amountPaidOnBuildingClaim",
    "totalBuildingInsuranceCoverage"
]].copy()

damage_value_issues

,claim_ref,source_system,state,dateOfLoss,buildingPropertyValue,buildingReplacementCost,buildingDamageAmount,amountPaidOnBuildingClaim,totalBuildingInsuranceCoverage
10,CLM-6726350,core,FL,2024-09-26 00:00:00+00:00,180686.0,358376.0,199577.0,189576.83,250000.0
12,CLM-7820778,core,FL,2024-09-27 00:00:00+00:00,0.0,0.0,191858.0,189857.65,250000.0
38,CLM-6601785,core,LA,2021-08-29 00:00:00+00:00,0.0,0.0,37970.0,36719.75,223000.0
76,CLM-6732637,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,107206.0,102205.57,250000.0
80,CLM-5826796,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,12165.0,10164.64,250000.0
118,CLM-8009009,core,KY,2021-03-08 00:00:00+00:00,0.0,0.0,6436.0,0.00,200000.0
134,CLM-6830799,core,TX,2019-09-17 00:00:00+00:00,149284.0,0.0,103.0,0.00,250000.0
198,CLM-6967195,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,113858.0,121230.38,149000.0
207,CLM-6018275,core,TX,2023-10-28 00:00:00+00:00,0.0,0.0,1.0,0.00,250000.0
257,CLM-6488458,core,FL,2024-09-27 00:00:00+00:00,0.0,0.0,12000.0,240936.03,250000.0
280,CLM-6906720,core,LA,2021-08-29 00:00:00+00:00,0.0,0.0,48119.0,46618.62,50000.0
303,CLM-7330184,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,1.0,14084.08,250000.0
311,CLM-5868777,core,FL,2022-10-04 00:00:00+00:00,0.0,0.0,1.0,33192.01,100000.0
356,CLM-6519081,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,5000.0,58357.65,200000.0
373,CLM-7279505,core,FL,2023-08-29 00:00:00+00:00,0.0,0.0,71250.0,66249.80,220000.0
384,CLM-6550216,core,FL,2024-09-27 00:00:00+00:00,0.0,0.0,92307.0,82306.62,218000.0
414,CLM-5543326,core,FL,2022-11-10 00:00:00+00:00,0.0,0.0,8261.0,6610.48,30000.0
447,CLM-6788159,core,WA,2020-02-06 00:00:00+00:00,148000.0,223050.0,163666.0,164206.58,165000.0
535,CLM-6925981,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,24107.0,22106.76,224000.0
543,CLM-7905386,core,TX,2024-05-02 00:00:00+00:00,0.0,0.0,48219.0,46219.05,250000.0
596,CLM-7716214,core,FL,2020-11-11 00:00:00+00:00,0.0,0.0,26779.0,28701.76,156100.0
615,CLM-8041105,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,114000.0,123302.16,250000.0
665,CLM-5632217,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,1.0,140521.19,250000.0
672,CLM-5893075,core,NY,2019-07-07 00:00:00+00:00,337682.0,0.0,11748.0,10498.46,250000.0
676,CLM-6900261,core,AR,2023-10-04 00:00:00+00:00,0.0,0.0,1.0,121342.48,250000.0
701,CLM-7032381,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,1.0,92289.46,163000.0
743,CLM-6179160,core,FL,2024-09-27 00:00:00+00:00,0.0,0.0,1.0,9586.20,250000.0
754,CLM-5500843,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,135856.0,144689.56,250000.0
829,CLM-5646266,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,210317.0,221860.94,250000.0
840,CLM-5669449,core,FL,2024-10-10 00:00:00+00:00,0.0,0.0,148042.0,156052.00,250000.0
862,CLM-5507607,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,13000.0,12203.93,250000.0
873,CLM-6145841,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,24799.0,22799.12,200000.0
884,CLM-6166211,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,14842.0,22094.50,250000.0
917,CLM-6061699,core,FL,2020-11-08 00:00:00+00:00,0.0,0.0,57972.0,61326.47,250000.0
943,CLM-7185471,core,MO,2022-07-26 00:00:00+00:00,213573.0,255329.0,1088937.0,205516.20,250000.0
947,CLM-7030610,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,358678.0,250000.00,250000.0
969,CLM-6345687,core,FL,2022-09-28 00:00:00+00:00,430363.0,0.0,164121.0,214121.18,250000.0
981,CLM-7804802,core,FL,2024-10-10 00:00:00+00:00,0.0,0.0,64101.0,62850.69,250000.0
1015,CLM-5536809,core,FL,2024-09-27 00:00:00+00:00,0.0,0.0,17749.0,13990.62,250000.0
1049,CLM-6309618,core,PA,2020-08-04 00:00:00+00:00,0.0,0.0,41771.0,38935.23,113000.0
1062,CLM-5939697,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,12395.0,12281.81,250000.0
1064,CLM-7961163,core,LA,2021-05-19 00:00:00+00:00,0.0,0.0,97622.0,93911.95,250000.0
1077,CLM-7164084,core,LA,2020-10-09 00:00:00+00:00,0.0,0.0,21613.0,20474.86,250000.0
1082,CLM-6100572,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,77000.0,82946.22,222000.0
1087,CLM-7294870,core,FL,2024-09-28 00:00:00+00:00,0.0,0.0,164796.0,154796.07,250000.0
1090,CLM-7244473,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,12701.0,7700.94,250000.0
1115,CLM-7738044,core,FL,2024-10-09 00:00:00+00:00,0.0,0.0,36845.0,34844.51,127000.0
1123,CLM-7548305,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,1.0,2010.12,250000.0
1126,CLM-5513532,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,192502.0,195124.73,250000.0
1147,CLM-8150954,core,FL,2024-09-26 00:00:00+00:00,21772.0,38546.0,23772.0,21772.58,66000.0
1221,CLM-6929169,legacy_bdx,KY,NaT,67642.0,220183.0,78213.0,90274.00,141000.0
1235,CLM-7018284,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,308019.0,250000.00,250000.0
1246,CLM-7011831,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,21344.0,17577.27,250000.0
1285,CLM-7783197,core,LA,2021-08-29 00:00:00+00:00,0.0,0.0,17640.0,16389.35,201000.0
1321,CLM-7532780,core,PA,2021-09-02 00:00:00+00:00,0.0,0.0,8147.0,6896.70,125000.0
1328,CLM-6812106,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,16133.0,30520.15,250000.0
1381,CLM-7244619,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,1.0,4378.99,250000.0
1453,CLM-6449644,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,507406.0,503935.50,1000000.0
1501,CLM-5470901,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,1.0,156000.00,156000.0
1503,CLM-5828697,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,227109.0,240513.35,250000.0
1511,CLM-7270798,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,1.0,122788.33,250000.0
1518,CLM-5651070,legacy_bdx,FL,NaT,0.0,0.0,150763.0,149513.00,250000.0
1558,CLM-8102217,core,FL,2024-09-30 00:00:00+00:00,0.0,0.0,120000.0,119754.27,250000.0
1559,CLM-7936455,core,TX,2021-05-16 00:00:00+00:00,0.0,0.0,7577.0,7083.21,200000.0
1582,CLM-5731667,core,FL,2022-09-28 00:00:00+00:00,0.0,1969208.0,13728.0,8808.64,250000.0
1591,CLM-5459928,core,FL,2022-09-28 00:00:00+00:00,348244.0,404935.0,354174.0,325000.00,500000.0
1600,CLM-5907432,core,TX,2020-06-01 00:00:00+00:00,0.0,0.0,5720.0,4469.43,150000.0
1670,CLM-7848284,core,TX,2019-09-19 00:00:00+00:00,0.0,0.0,38486.0,99371.40,250000.0
1671,CLM-6274101,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,97217.0,104173.16,250000.0
1674,CLM-8087807,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,1.0,49675.74,250000.0
1677,CLM-6145841-R,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,24799.0,22799.12,200000.0
1686,CLM-7282771,core,FL,2022-09-28 00:00:00+00:00,0.0,0.0,1.0,10652.24,250000.0
1688,CLM-7936455-R,core,TX,2021-05-16 00:00:00+00:00,0.0,0.0,7577.0,7083.21,200000.0
1806,CLM-7871324,core,MO,2024-07-16 00:00:00+00:00,0.0,0.0,1.0,6136.44,250000.0
1896,CLM-7300874,core,FL,2023-08-30 00:00:00+00:00,0.0,0.0,4229.0,2228.82,250000.0
1941,CLM-5840371,core,FL,2024-09-26 00:00:00+00:00,0.0,0.0,81627.0,71626.54,220000.0
1942,CLM-5632534,core,SC,2022-09-30 00:00:00+00:00,0.0,330013.0,37254.0,35254.17,250000.0
2000,CLM-5472105,core,TX,2024-07-08 00:00:00+00:00,0.0,0.0,61620.0,57985.49,191000.0
2003,CLM-7169458,core,TX,2019-09-20 00:00:00+00:00,0.0,0.0,6154.0,10273.12,250000.0
2038,CLM-6629976,core,GA,2024-09-26 00:00:00+00:00,0.0,0.0,1.0,5342.14,223000.0

## Clean 5
Replaced 0 buildingPropertyValue with nan. 

Replaced 0 buildingReplacementCost with nan.

In [60]:
import numpy as np

In [61]:
df_clean.loc[
    df_clean["buildingPropertyValue"] == 0,
    "buildingPropertyValue"
] = np.nan

df_clean.loc[
    df_clean["buildingReplacementCost"] == 0,
    "buildingReplacementCost"
] = np.nan

### Several business-logic inconsistencies were identified, including damage exceeding reported property/replacement values and payments exceeding reported coverage. I retained these because the available fields do not establish that these relationships are strict constraints. Modifying them would risk fabricating values.

In [62]:
df_clean[
    (df_clean["amountPaidOnBuildingClaim"] < 0) |
    (df_clean["amountPaidOnContentsClaim"] < 0) |
    (df_clean["netBuildingPaymentAmount"] < 0)
][[
    "claim_ref",
    "source_system",
    "amountPaidOnBuildingClaim",
    "amountPaidOnContentsClaim",
    "netBuildingPaymentAmount",
    "nonPaymentReasonBuilding"
]]

,claim_ref,source_system,amountPaidOnBuildingClaim,amountPaidOnContentsClaim,netBuildingPaymentAmount,nonPaymentReasonBuilding
330,CLM-7980100,legacy_bdx,-5000.0,-1000.0,-5000.0,98.0

In [72]:
base_ref = df_clean["claim_ref"].str.replace("-R$", "", regex=True)

df_clean[base_ref.duplicated(keep=False)][[
    "claim_ref",
    "source_system",
    "dateOfLoss",
    "state",
    "buildingDamageAmount",
    "amountPaidOnBuildingClaim"
]].sort_values("claim_ref")

,claim_ref,source_system,dateOfLoss,state,buildingDamageAmount,amountPaidOnBuildingClaim
1323,CLM-5457646,core,2021-08-29 00:00:00+00:00,NY,7269.0,6019.22
1711,CLM-5457646-R,core,2021-08-29 00:00:00+00:00,NY,7269.0,6019.22
1167,CLM-5589318,core,2023-08-30 00:00:00+00:00,FL,87790.0,92013.12
1775,CLM-5589318-R,core,2023-08-30 00:00:00+00:00,FL,87790.0,92013.12
1676,CLM-5598359,legacy_bdx,NaT,CA,0.0,0.00
1211,CLM-5598359-R,legacy_bdx,NaT,CA,0.0,0.00
763,CLM-5615193,core,2018-09-14 00:00:00+00:00,NC,3034.0,1784.72
1694,CLM-5615193-R,core,2018-09-14 00:00:00+00:00,NC,3034.0,1784.72
1005,CLM-5690103,core,2021-01-15 00:00:00+00:00,MD,NaN,NaN
1074,CLM-5690103-R,core,2021-01-15 00:00:00+00:00,MD,NaN,NaN
1712,CLM-6002479,core,2022-09-27 00:00:00+00:00,FL,6717.0,4717.40
1719,CLM-6002479-R,core,2022-09-27 00:00:00+00:00,FL,6717.0,4717.40
1355,CLM-6009600,core,2024-10-09 00:00:00+00:00,FL,7103.0,5103.07
1710,CLM-6009600-R,core,2024-10-09 00:00:00+00:00,FL,7103.0,5103.07
312,CLM-6053137,core,2022-09-28 00:00:00+00:00,FL,45053.0,35052.80
902,CLM-6053137-R,core,2022-09-28 00:00:00+00:00,FL,45053.0,35052.80
873,CLM-6145841,core,2024-09-26 00:00:00+00:00,FL,24799.0,22799.12
1677,CLM-6145841-R,core,2024-09-26 00:00:00+00:00,FL,24799.0,22799.12
1250,CLM-6229538,core,2018-10-27 00:00:00+00:00,NJ,12226.0,8055.78
378,CLM-6229538-R,core,2018-10-27 00:00:00+00:00,NJ,12226.0,8055.78
1652,CLM-6268837,core,2019-06-23 00:00:00+00:00,MO,1871.0,871.33
1336,CLM-6268837-R,core,2019-06-23 00:00:00+00:00,MO,1871.0,871.33
1807,CLM-6521778,core,2024-09-26 00:00:00+00:00,FL,74625.0,76826.67
299,CLM-6521778-R,core,2024-09-26 00:00:00+00:00,FL,74625.0,76826.67
1796,CLM-6576331,core,2024-05-16 00:00:00+00:00,TX,0.0,0.00
949,CLM-6576331-R,core,2024-05-16 00:00:00+00:00,TX,0.0,0.00
1782,CLM-6581402,core,2021-08-29 00:00:00+00:00,LA,80563.0,83907.45
1173,CLM-6581402-R,core,2021-08-29 00:00:00+00:00,LA,80563.0,83907.45
430,CLM-6597136,core,2022-09-06 00:00:00+00:00,TX,27863.0,30591.15
1488,CLM-6597136-R,core,2022-09-06 00:00:00+00:00,TX,27863.0,30591.15
1165,CLM-6613036,core,2022-09-28 00:00:00+00:00,FL,85867.0,84617.16
1547,CLM-6613036-R,core,2022-09-28 00:00:00+00:00,FL,85867.0,84617.16
490,CLM-6658432,core,2022-05-21 00:00:00+00:00,PA,0.0,1293.62
1222,CLM-6658432-R,core,2022-05-21 00:00:00+00:00,PA,0.0,1293.62
47,CLM-6678785,core,2018-10-10 00:00:00+00:00,FL,NaN,NaN
1254,CLM-6678785-R,core,2018-10-10 00:00:00+00:00,FL,NaN,NaN
1877,CLM-6839569,core,2024-09-26 00:00:00+00:00,FL,0.0,NaN
29,CLM-6839569-R,core,2024-09-26 00:00:00+00:00,FL,0.0,NaN
1812,CLM-6881275,core,2020-06-25 00:00:00+00:00,FL,14326.0,4501.62
1085,CLM-6881275-R,core,2020-06-25 00:00:00+00:00,FL,14326.0,4501.62
1665,CLM-6888019,core,2024-09-29 00:00:00+00:00,FL,23372.0,23467.52
1384,CLM-6888019-R,core,2024-09-29 00:00:00+00:00,FL,23372.0,23467.52
810,CLM-7124335,core,2025-07-06 00:00:00+00:00,NC,275633.0,250000.00
314,CLM-7124335-R,core,2025-07-06 00:00:00+00:00,NC,275633.0,250000.00
1317,CLM-7127665,legacy_bdx,NaT,TX,10031.0,9465.00
186,CLM-7127665-R,legacy_bdx,NaT,TX,10031.0,9465.00
219,CLM-7433935,core,2020-11-08 00:00:00+00:00,FL,0.0,0.00
133,CLM-7433935-R,core,2020-11-08 00:00:00+00:00,FL,0.0,0.00
1319,CLM-7446191,core,2022-09-28 00:00:00+00:00,FL,17988.0,15989.63
1103,CLM-7446191-R,core,2022-09-28 00:00:00+00:00,FL,17988.0,15989.63
794,CLM-7449518,core,2024-10-09 00:00:00+00:00,FL,131219.0,129219.05
777,CLM-7449518-R,core,2024-10-09 00:00:00+00:00,FL,131219.0,129219.05
1973,CLM-7468945,core,2024-09-26 00:00:00+00:00,FL,56467.0,55467.92
944,CLM-7468945-R,core,2024-09-26 00:00:00+00:00,FL,56467.0,55467.92
194,CLM-7495589,core,2018-08-13 00:00:00+00:00,PA,17504.0,19716.96
923,CLM-7495589-R,core,2018-08-13 00:00:00+00:00,PA,17504.0,19716.96
1280,CLM-7621754,core,2021-08-29 00:00:00+00:00,LA,123395.0,70000.00
1645,CLM-7621754-R,core,2021-08-29 00:00:00+00:00,LA,123395.0,70000.00
1718,CLM-7685251,core,2018-08-13 00:00:00+00:00,PA,3811.0,1811.64
1862,CLM-7685251-R,core,2018-08-13 00:00:00+00:00,PA,3811.0,1811.64
428,CLM-7773144,core,2024-09-26 00:00:00+00:00,FL,122034.0,112033.17
719,CLM-7773144-R,core,2024-09-26 00:00:00+00:00,FL,122034.0,112033.17
775,CLM-7804614,core,2022-09-28 00:00:00+00:00,FL,190251.0,185250.77
1932,CLM-7804614-R,core,2022-09-28 00:00:00+00:00,FL,190251.0,185250.77
1559,CLM-7936455,core,2021-05-16 00:00:00+00:00,TX,7577.0,7083.21
1688,CLM-7936455-R,core,2021-05-16 00:00:00+00:00,TX,7577.0,7083.21
909,CLM-8004037,core,2024-09-26 00:00:00+00:00,FL,84961.0,79961.42
990,CLM-8004037-R,core,2024-09-26 00:00:00+00:00,FL,84961.0,79961.42
1207,CLM-8041087,core,2021-06-19 00:00:00+00:00,LA,75965.0,90601.45
529,CLM-8041087-R,core,2021-06-19 00:00:00+00:00,LA,75965.0,90601.45
556,CLM-8057769,core,2021-09-01 00:00:00+00:00,NY,23185.0,21935.14
137,CLM-8057769-R,core,2021-09-01 00:00:00+00:00,NY,23185.0,21935.14
1327,CLM-8072327,core,2020-09-16 00:00:00+00:00,FL,142469.0,166218.78
1844,CLM-8072327-R,core,2020-09-16 00:00:00+00:00,FL,142469.0,166218.78
364,CLM-8106199,legacy_bdx,NaT,FL,87210.0,77210.00
1696,CLM-8106199-R,legacy_bdx,NaT,FL,87210.0,77210.00
403,CLM-8109648,core,2021-06-19 00:00:00+00:00,LA,42209.0,40810.86
580,CLM-8109648-R,core,2021-06-19 00:00:00+00:00,LA,42209.0,40810.86
1345,CLM-8140690,core,2018-04-14 00:00:00+00:00,AL,34533.0,40043.04
227,CLM-8140690-R,core,2018-04-14 00:00:00+00:00,AL,34533.0,40043.04

## Clean 6
Replacing negative amoutnPaid col with nan

In [66]:
neg_payment_mask = (
    (df_clean["amountPaidOnBuildingClaim"] < 0) |
    (df_clean["amountPaidOnContentsClaim"] < 0) |
    (df_clean["netBuildingPaymentAmount"] < 0)
)

df_clean.loc[neg_payment_mask, [
    "amountPaidOnBuildingClaim",
    "amountPaidOnContentsClaim",
    "netBuildingPaymentAmount"
]] = np.nan

In [69]:
df_clean["base_claim_ref"] = df_clean["claim_ref"].str.replace(
    r"-R$",
    "",
    regex=True
)

base_counts = df_clean["base_claim_ref"].value_counts()

base_counts[base_counts > 1].head(200)

base_claim_ref
CLM-6839569    2
CLM-6678785    2
CLM-7433935    2
CLM-8057769    2
CLM-7127665    2
CLM-7495589    2
CLM-8140690    2
CLM-6521778    2
CLM-6053137    2
CLM-7124335    2
CLM-8106199    2
CLM-6229538    2
CLM-8109648    2
CLM-7773144    2
CLM-6597136    2
CLM-6658432    2
CLM-8041087    2
CLM-5615193    2
CLM-7804614    2
CLM-7449518    2
CLM-6145841    2
CLM-8004037    2
CLM-7468945    2
CLM-6576331    2
CLM-5690103    2
CLM-6881275    2
CLM-7446191    2
CLM-6613036    2
CLM-5589318    2
CLM-6581402    2
CLM-5598359    2
CLM-7621754    2
CLM-5457646    2
CLM-8072327    2
CLM-6268837    2
CLM-6009600    2
CLM-6888019    2
CLM-7936455    2
CLM-6002479    2
CLM-7685251    2
Name: count, dtype: int64

## Clean 7
Removing dups

In [73]:
r_mask = df_clean["claim_ref"].str.endswith("-R")

print("R duplicate rows:", r_mask.sum())

df_clean = df_clean[~r_mask].copy()

print("Rows after removing duplicates:", len(df_clean))

R duplicate rows: 40
Rows after removing duplicates: 2000

In [74]:
df_clean["claim_ref"].str.endswith("-R").sum()

np.int64(0)

In [75]:
for col in [
    "causeOfDamage",
    "ratedFloodZone",
    "occupancyType",
    "nonPaymentReasonBuilding"
]:
    print("\n", col)
    print(df_clean[col].value_counts(dropna=False))

 causeOfDamage
causeOfDamage
4      892
1      446
2      394
0      237
NaN     27
D        3
3        1
Name: count, dtype: int64

 ratedFloodZone
ratedFloodZone
AE     1270
X       437
A        93
VE       65
AH       31
C        25
AO       21
B        11
NaN       5
A08       5
A99       5
A13       4
A10       4
A09       3
A04       3
A05       2
A15       2
A07       2
A01       2
A12       2
AHB       1
A11       1
A18       1
A02       1
V16       1
AOB       1
D         1
A03       1
Name: count, dtype: int64

 occupancyType
occupancyType
11    1279
1      306
18     118
15      92
12      61
13      35
14      30
16      27
6       25
3       14
2       10
4        3
Name: count, dtype: int64

 nonPaymentReasonBuilding
nonPaymentReasonBuilding
NaN     1616
6.0      108
99.0      74
1.0       70
97.0      60
20.0      38
98.0      19
8.0       10
16.0       2
7.0        2
15.0       1
Name: count, dtype: int64

In [76]:
missing = (
    df_clean.isna()
    .sum()
    .to_frame("missing")
)

missing["missing_pct"] = missing["missing"] / len(df_clean) * 100

missing.sort_values("missing_pct", ascending=False)

                                    missing  missing_pct
nonPaymentReasonBuilding               1616        80.80
floodWaterDuration                     1579        78.95
contentsDamageAmount                    886        44.30
floodEvent                              551        27.55
buildingPropertyValue                   375        18.75
buildingReplacementCost                 375        18.75
waterDepth                              305        15.25
buildingDamageAmount                    218        10.90
mostRecentPaymentDate                   197         9.85
amountPaidOnContentsClaim               192         9.60
amountPaidOnBuildingClaim               190         9.50
dateOfLoss                              120         6.00
causeOfDamage                            27         1.35
originalConstructionDate                 24         1.20
latitude                                 17         0.85
longitude                                14         0.70
numberOfFloorsInTheInsuredBuilding       10         0.50
countyCode                                9         0.45
ratedFloodZone                            5         0.25
netBuildingPaymentAmount                  1         0.05
yearOfLoss                                0         0.00
source_system                             0         0.00
state                                     0         0.00
claim_ref                                 0         0.00
elevatedBuildingIndicator                 0         0.00
occupancyType                             0         0.00
reportedZipCode                           0         0.00
totalContentsInsuranceCoverage            0         0.00
totalBuildingInsuranceCoverage            0         0.00
primaryResidenceIndicator                 0         0.00
openDate                                  0         0.00
base_claim_ref                            0         0.00

In [77]:
df_clean[df_clean["dateOfLoss"].isna()]["source_system"].value_counts()

source_system
legacy_bdx    120
Name: count, dtype: int64

In [83]:
df_clean.loc[
    df_clean["dateOfLoss"].isna(),
    ["claim_ref", "source_system", "dateOfLoss"]
]

        claim_ref source_system dateOfLoss
40    CLM-7898726    legacy_bdx        NaT
67    CLM-5746454    legacy_bdx        NaT
82    CLM-6157209    legacy_bdx        NaT
99    CLM-6470168    legacy_bdx        NaT
144   CLM-6398916    legacy_bdx        NaT
154   CLM-7011673    legacy_bdx        NaT
156   CLM-5725175    legacy_bdx        NaT
158   CLM-5848380    legacy_bdx        NaT
165   CLM-8169782    legacy_bdx        NaT
168   CLM-6916300    legacy_bdx        NaT
211   CLM-6799102    legacy_bdx        NaT
235   CLM-6409025    legacy_bdx        NaT
250   CLM-7337861    legacy_bdx        NaT
318   CLM-6134163    legacy_bdx        NaT
330   CLM-7980100    legacy_bdx        NaT
345   CLM-5897469    legacy_bdx        NaT
364   CLM-8106199    legacy_bdx        NaT
379   CLM-7326132    legacy_bdx        NaT
385   CLM-7159386    legacy_bdx        NaT
393   CLM-7701299    legacy_bdx        NaT
432   CLM-6877029    legacy_bdx        NaT
456   CLM-6304365    legacy_bdx        NaT
471   CLM-7648582    legacy_bdx        NaT
479   CLM-8024729    legacy_bdx        NaT
484   CLM-6410405    legacy_bdx        NaT
489   CLM-6729784    legacy_bdx        NaT
504   CLM-6134144    legacy_bdx        NaT
521   CLM-5597390    legacy_bdx        NaT
527   CLM-6611416    legacy_bdx        NaT
568   CLM-5955654    legacy_bdx        NaT
569   CLM-6350855    legacy_bdx        NaT
586   CLM-8004040    legacy_bdx        NaT
589   CLM-6798980    legacy_bdx        NaT
607   CLM-6015489    legacy_bdx        NaT
628   CLM-6116476    legacy_bdx        NaT
650   CLM-7132163    legacy_bdx        NaT
651   CLM-5651249    legacy_bdx        NaT
653   CLM-5619471    legacy_bdx        NaT
659   CLM-5662806    legacy_bdx        NaT
675   CLM-7806776    legacy_bdx        NaT
693   CLM-6262285    legacy_bdx        NaT
695   CLM-6339582    legacy_bdx        NaT
702   CLM-6885506    legacy_bdx        NaT
715   CLM-7529391    legacy_bdx        NaT
726   CLM-5752148    legacy_bdx        NaT
729   CLM-7791153    legacy_bdx        NaT
734   CLM-6972218    legacy_bdx        NaT
769   CLM-7658310    legacy_bdx        NaT
770   CLM-7515271    legacy_bdx        NaT
783   CLM-6155617    legacy_bdx        NaT
799   CLM-6150668    legacy_bdx        NaT
824   CLM-6043281    legacy_bdx        NaT
833   CLM-6638809    legacy_bdx        NaT
846   CLM-6505015    legacy_bdx        NaT
896   CLM-5686745    legacy_bdx        NaT
900   CLM-8111208    legacy_bdx        NaT
910   CLM-7830371    legacy_bdx        NaT
913   CLM-8091327    legacy_bdx        NaT
918   CLM-7611973    legacy_bdx        NaT
957   CLM-7548551    legacy_bdx        NaT
960   CLM-7498965    legacy_bdx        NaT
1026  CLM-7579642    legacy_bdx        NaT
1057  CLM-7137299    legacy_bdx        NaT
1066  CLM-7010576    legacy_bdx        NaT
1069  CLM-7576391    legacy_bdx        NaT
1092  CLM-5616891    legacy_bdx        NaT
1096  CLM-6556909    legacy_bdx        NaT
1116  CLM-6665337    legacy_bdx        NaT
1149  CLM-6281112    legacy_bdx        NaT
1158  CLM-7923440    legacy_bdx        NaT
1171  CLM-8039125    legacy_bdx        NaT
1221  CLM-6929169    legacy_bdx        NaT
1224  CLM-6711528    legacy_bdx        NaT
1256  CLM-5740689    legacy_bdx        NaT
1317  CLM-7127665    legacy_bdx        NaT
1340  CLM-5455528    legacy_bdx        NaT
1349  CLM-7214174    legacy_bdx        NaT
1395  CLM-6217820    legacy_bdx        NaT
1400  CLM-7509126    legacy_bdx        NaT
1413  CLM-6478790    legacy_bdx        NaT
1424  CLM-6227325    legacy_bdx        NaT
1434  CLM-6590305    legacy_bdx        NaT
1451  CLM-7783607    legacy_bdx        NaT
1504  CLM-8061788    legacy_bdx        NaT
1518  CLM-5651070    legacy_bdx        NaT
1525  CLM-6688953    legacy_bdx        NaT
1567  CLM-6092826    legacy_bdx        NaT
1575  CLM-6115415    legacy_bdx        NaT
1581  CLM-6402440    legacy_bdx        NaT
1602  CLM-7712016    legacy_bdx        NaT
1623  CLM-6240330    legacy_bdx        NaT
1646  CLM-5678461    legacy_bdx        NaT
1649  CLM-7105582    legacy_bdx        NaT
1672  CLM-5816219    legacy_bdx        NaT
1675  CLM-7611646    legacy_bdx        NaT
1676  CLM-5598359    legacy_bdx        NaT
1681  CLM-6913763    legacy_bdx        NaT
1692  CLM-6732332    legacy_bdx        NaT
1729  CLM-6798651    legacy_bdx        NaT
1752  CLM-5720147    legacy_bdx        NaT
1773  CLM-8146860    legacy_bdx        NaT
1789  CLM-6327028    legacy_bdx        NaT
1818  CLM-8021886    legacy_bdx        NaT
1824  CLM-6381987    legacy_bdx        NaT
1847  CLM-5841675    legacy_bdx        NaT
1848  CLM-6942553    legacy_bdx        NaT
1870  CLM-5597136    legacy_bdx        NaT
1883  CLM-8068671    legacy_bdx        NaT
1893  CLM-5794073    legacy_bdx        NaT
1918  CLM-6931120    legacy_bdx        NaT
1919  CLM-6238862    legacy_bdx        NaT
1920  CLM-6298272    legacy_bdx        NaT
1946  CLM-6680557    legacy_bdx        NaT
1950  CLM-7047002    legacy_bdx        NaT
1977  CLM-6775386    legacy_bdx        NaT
1988  CLM-6032235    legacy_bdx        NaT
1995  CLM-5706636    legacy_bdx        NaT
2004  CLM-5554211    legacy_bdx        NaT
2010  CLM-5693679    legacy_bdx        NaT
2022  CLM-7413975    legacy_bdx        NaT

In [82]:
df.loc[
    df["claim_ref"].isin(missing_loss_claims),
    ["claim_ref", "source_system", "dateOfLoss"]
]

        claim_ref source_system  dateOfLoss
40    CLM-7898726    legacy_bdx  29-09-2023
67    CLM-5746454    legacy_bdx  30-08-2023
82    CLM-6157209    legacy_bdx  10-10-2024
99    CLM-6470168    legacy_bdx  09-10-2024
144   CLM-6398916    legacy_bdx  30-09-2022
154   CLM-7011673    legacy_bdx  05-04-2025
156   CLM-5725175    legacy_bdx  23-03-2026
158   CLM-5848380    legacy_bdx  30-09-2022
165   CLM-8169782    legacy_bdx  19-05-2020
168   CLM-6916300    legacy_bdx  21-04-2025
211   CLM-6799102    legacy_bdx  04-08-2019
235   CLM-6409025    legacy_bdx  21-08-2025
250   CLM-7337861    legacy_bdx  26-09-2024
318   CLM-6134163    legacy_bdx  26-09-2024
330   CLM-7980100    legacy_bdx  05-09-2019
345   CLM-5897469    legacy_bdx  14-09-2018
364   CLM-8106199    legacy_bdx  13-06-2024
379   CLM-7326132    legacy_bdx  13-09-2018
385   CLM-7159386    legacy_bdx  11-01-2020
393   CLM-7701299    legacy_bdx  06-09-2019
432   CLM-6877029    legacy_bdx  21-04-2025
456   CLM-6304365    legacy_bdx  27-03-2026
471   CLM-7648582    legacy_bdx  28-09-2022
479   CLM-8024729    legacy_bdx  16-02-2021
484   CLM-6410405    legacy_bdx  20-03-2019
489   CLM-6729784    legacy_bdx  23-09-2018
504   CLM-6134144    legacy_bdx  05-09-2020
521   CLM-5597390    legacy_bdx  20-08-2023
527   CLM-6611416    legacy_bdx  27-03-2021
568   CLM-5955654    legacy_bdx  14-03-2019
569   CLM-6350855    legacy_bdx  12-07-2019
586   CLM-8004040    legacy_bdx  28-05-2026
589   CLM-6798980    legacy_bdx  24-02-2018
607   CLM-6015489    legacy_bdx  29-08-2021
628   CLM-6116476    legacy_bdx  19-02-2020
650   CLM-7132163    legacy_bdx  27-09-2024
651   CLM-5651249    legacy_bdx  16-08-2018
653   CLM-5619471    legacy_bdx  27-09-2024
659   CLM-5662806    legacy_bdx  21-07-2026
675   CLM-7806776    legacy_bdx  10-10-2018
693   CLM-6262285    legacy_bdx  29-08-2021
695   CLM-6339582    legacy_bdx  26-09-2024
702   CLM-6885506    legacy_bdx  15-03-2019
715   CLM-7529391    legacy_bdx  01-09-2021
726   CLM-5752148    legacy_bdx  27-09-2024
729   CLM-7791153    legacy_bdx  11-11-2020
734   CLM-6972218    legacy_bdx  29-09-2023
769   CLM-7658310    legacy_bdx  26-09-2024
770   CLM-7515271    legacy_bdx  27-09-2022
783   CLM-6155617    legacy_bdx  13-09-2018
799   CLM-6150668    legacy_bdx  26-09-2024
824   CLM-6043281    legacy_bdx  20-02-2019
833   CLM-6638809    legacy_bdx  14-09-2018
846   CLM-6505015    legacy_bdx  05-02-2019
896   CLM-5686745    legacy_bdx  01-09-2021
900   CLM-8111208    legacy_bdx  25-06-2020
910   CLM-7830371    legacy_bdx  14-09-2018
913   CLM-8091327    legacy_bdx  26-09-2024
918   CLM-7611973    legacy_bdx  26-09-2024
957   CLM-7548551    legacy_bdx  20-05-2025
960   CLM-7498965    legacy_bdx  02-09-2021
1026  CLM-7579642    legacy_bdx  19-06-2021
1057  CLM-7137299    legacy_bdx  10-06-2021
1066  CLM-7010576    legacy_bdx  28-09-2022
1069  CLM-7576391    legacy_bdx  17-02-2018
1092  CLM-5616891    legacy_bdx  29-08-2021
1096  CLM-6556909    legacy_bdx  09-10-2020
1116  CLM-6665337    legacy_bdx  16-09-2018
1149  CLM-6281112    legacy_bdx  01-09-2021
1158  CLM-7923440    legacy_bdx  17-12-2023
1171  CLM-8039125    legacy_bdx  28-09-2022
1221  CLM-6929169    legacy_bdx  28-07-2022
1224  CLM-6711528    legacy_bdx  10-10-2018
1256  CLM-5740689    legacy_bdx  02-08-2026
1317  CLM-7127665    legacy_bdx  03-09-2018
1340  CLM-5455528    legacy_bdx  12-08-2026
1349  CLM-7214174    legacy_bdx  26-07-2022
1395  CLM-6217820    legacy_bdx  26-09-2024
1400  CLM-7509126    legacy_bdx  01-01-2023
1413  CLM-6478790    legacy_bdx  15-03-2019
1424  CLM-6227325    legacy_bdx  29-08-2021
1434  CLM-6590305    legacy_bdx  30-09-2022
1451  CLM-7783607    legacy_bdx  27-09-2022
1504  CLM-8061788    legacy_bdx  18-06-2021
1518  CLM-5651070    legacy_bdx  28-09-2022
1525  CLM-6688953    legacy_bdx  29-05-2023
1567  CLM-6092826    legacy_bdx  28-09-2022
1575  CLM-6115415    legacy_bdx  28-09-2022
1581  CLM-6402440    legacy_bdx  02-07-2023
1602  CLM-7712016    legacy_bdx  12-04-2023
1623  CLM-6240330    legacy_bdx  28-09-2022
1646  CLM-5678461    legacy_bdx  30-08-2023
1649  CLM-7105582    legacy_bdx  09-10-2024
1672  CLM-5816219    legacy_bdx  15-08-2026
1675  CLM-7611646    legacy_bdx  01-09-2021
1676  CLM-5598359    legacy_bdx  10-03-2023
1681  CLM-6913763    legacy_bdx  09-08-2024
1692  CLM-6732332    legacy_bdx  27-09-2024
1729  CLM-6798651    legacy_bdx  06-05-2022
1752  CLM-5720147    legacy_bdx  03-08-2020
1773  CLM-8146860    legacy_bdx  28-09-2022
1789  CLM-6327028    legacy_bdx  29-08-2021
1818  CLM-8021886    legacy_bdx  07-04-2025
1824  CLM-6381987    legacy_bdx  16-04-2018
1847  CLM-5841675    legacy_bdx  28-09-2022
1848  CLM-6942553    legacy_bdx  19-09-2019
1870  CLM-5597136    legacy_bdx  19-09-2019
1883  CLM-8068671    legacy_bdx  06-06-2019
1893  CLM-5794073    legacy_bdx  26-09-2024
1918  CLM-6931120    legacy_bdx  13-09-2018
1919  CLM-6238862    legacy_bdx  28-09-2022
1920  CLM-6298272    legacy_bdx  26-09-2024
1946  CLM-6680557    legacy_bdx  12-04-2023
1950  CLM-7047002    legacy_bdx  12-07-2019
1977  CLM-6775386    legacy_bdx  09-10-2024
1988  CLM-6032235    legacy_bdx  15-09-2021
1995  CLM-5706636    legacy_bdx  21-06-2018
2004  CLM-5554211    legacy_bdx  19-09-2019
2010  CLM-5693679    legacy_bdx  29-08-2021
2022  CLM-7413975    legacy_bdx  30-08-2023

In [86]:
raw_loss = df["dateOfLoss"].astype("string").str.strip()

parsed_loss = pd.Series(
    pd.NaT,
    index=df.index,
    dtype="datetime64[ns, UTC]"
)

# Core: YYYY-MM-DDTHH:MM:SS.sssZ
core_mask = df["source_system"].eq("core")

parsed_loss.loc[core_mask] = pd.to_datetime(
    raw_loss.loc[core_mask],
    format="%Y-%m-%dT%H:%M:%S.%fZ",
    errors="coerce",
    utc=True
)

# Legacy: DD-MM-YYYY
legacy_mask = df["source_system"].eq("legacy_bdx")

parsed_loss.loc[legacy_mask] = pd.to_datetime(
    raw_loss.loc[legacy_mask],
    format="%d-%m-%Y",
    errors="coerce",
    utc=True
)

# Map back to the cleaned dataframe
date_map = pd.Series(
    parsed_loss.values,
    index=df["claim_ref"]
)

df_clean["dateOfLoss"] = df_clean["claim_ref"].map(date_map)

In [87]:
print("Missing dateOfLoss:", df_clean["dateOfLoss"].isna().sum())
print(df_clean["dateOfLoss"].min())
print(df_clean["dateOfLoss"].max())

Missing dateOfLoss: 0
2018-01-04 00:00:00
2026-08-20 00:00:00

In [88]:
print("Shape:", df_clean.shape)

print("\nDuplicate rows:", df_clean.duplicated().sum())
print("Duplicate claim_ref:", df_clean["claim_ref"].duplicated().sum())

print("\nMissing dateOfLoss:", df_clean["dateOfLoss"].isna().sum())
print("Missing openDate:", df_clean["openDate"].isna().sum())

print("\nInvalid latitude:",
      ((df_clean["latitude"] < -90) |
       (df_clean["latitude"] > 90)).sum())

print("\nNegative payments:")
print(
    (
        (df_clean["amountPaidOnBuildingClaim"] < 0) |
        (df_clean["amountPaidOnContentsClaim"] < 0) |
        (df_clean["netBuildingPaymentAmount"] < 0)
    ).sum()
)

Shape: (2000, 32)

Duplicate rows: 0
Duplicate claim_ref: 0

Missing dateOfLoss: 0
Missing openDate: 0

Invalid latitude: 0

Negative payments:
0

In [91]:
date_cols = [
    "dateOfLoss",
    "openDate",
    "originalConstructionDate",
    "mostRecentPaymentDate"
]

for col in date_cols:
    df_clean[col] = pd.to_datetime(
        df_clean[col],
        errors="coerce",
        utc=True
    )

In [92]:
print(
    "Payment before loss:",
    (df_clean["mostRecentPaymentDate"] < df_clean["dateOfLoss"]).sum()
)

print(
    "Construction after loss:",
    (df_clean["originalConstructionDate"] > df_clean["dateOfLoss"]).sum()
)

print(
    "Open date before loss:",
    (df_clean["openDate"] < df_clean["dateOfLoss"]).sum()
)

Payment before loss: 0
Construction after loss: 0
Open date before loss: 0

In [93]:
df_clean[
    df_clean["ratedFloodZone"].isin(["AHB", "AOB", "D"])
][[
    "claim_ref",
    "state",
    "reportedZipCode",
    "ratedFloodZone",
    "floodEvent"
]]

,claim_ref,state,reportedZipCode,ratedFloodZone,floodEvent
66,CLM-7986783,TX,78503,AHB,NaN
879,CLM-7990756,CA,93065,AOB,NaN
1397,CLM-7651852,CA,91040,D,California Atmospheric River

In [94]:
df_clean = df_clean.drop(columns=["base_claim_ref"])

In [98]:
print((df_clean["longitude"] < -90).any())

True

In [95]:
# Make sure temporary investigation columns are removed
if "base_claim_ref" in df_clean.columns:
    df_clean = df_clean.drop(columns=["base_claim_ref"])

# Save cleaned dataset
df_clean.to_csv("nfip_claims_cleaned.csv", index=False)

print("Saved cleaned dataset")
print("Shape:", df_clean.shape)

Saved cleaned dataset
Shape: (2000, 31)

In [97]:
print("Shape:", df_clean.shape)
print("Duplicate rows:", df_clean.duplicated().sum())
print("Duplicate claim_ref:", df_clean["claim_ref"].duplicated().sum())

print("Missing dateOfLoss:", df_clean["dateOfLoss"].isna().sum())
print("Missing openDate:", df_clean["openDate"].isna().sum())

print(
    "Invalid latitude:",
    ((df_clean["latitude"] < -90) | (df_clean["latitude"] > 90)).sum()
)

print(
    "Negative payments:",
    (
        (df_clean["amountPaidOnBuildingClaim"] < 0) |
        (df_clean["amountPaidOnContentsClaim"] < 0) |
        (df_clean["netBuildingPaymentAmount"] < 0)
    ).sum()
)

print(
    "Payment before loss:",
    (
        df_clean["mostRecentPaymentDate"] < df_clean["dateOfLoss"]
    ).sum()
)

print(
    "Construction after loss:",
    (
        df_clean["originalConstructionDate"] > df_clean["dateOfLoss"]
    ).sum()
)

Shape: (2000, 31)
Duplicate rows: 0
Duplicate claim_ref: 0
Missing dateOfLoss: 0
Missing openDate: 0
Invalid latitude: 0
Negative payments: 0
Payment before loss: 0
Construction after loss: 0